CREATE TABLE "caplets"."cp_setup_execution" (
	"model_version" bigint NOT NULL,
	"id" text NOT NULL,
	"logical_host_id" text NOT NULL,
	"store_id" text NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL,
	"aggregate_version" bigint NOT NULL,
	"authority_version" bigint NOT NULL,
	"effective_version" bigint NOT NULL,
	"security_version" bigint NOT NULL,
	"execution_id" text NOT NULL,
	"project_fingerprint" text NOT NULL,
	"caplet_id" text NOT NULL,
	"content_hash" text NOT NULL,
	"setup_hash" text,
	"target_kind" text NOT NULL,
	"lease_id" text NOT NULL,
	"reserved_at" text NOT NULL,
	"expires_at" text NOT NULL,
	"state" text NOT NULL,
	CONSTRAINT "cp_setup_execution_pk" PRIMARY KEY("logical_host_id","id"),
	CONSTRAINT "cp_setup_execution_model_version_version_check" CHECK ("caplets"."cp_setup_execution"."model_version" >= 0),
	CONSTRAINT "cp_setup_execution_id_nonempty_check" CHECK (length("caplets"."cp_setup_execution"."id") > 0),
	CONSTRAINT "cp_setup_execution_logical_host_id_nonempty_check" CHECK (length("caplets"."cp_setup_execution"."logical_host_id") > 0),
	CONSTRAINT "cp_setup_execution_store_id_nonempty_check" CHECK (length("caplets"."cp_setup_execution"."store_id") > 0),
	CONSTRAINT "cp_setup_execution_created_at_nonempty_check" CHECK (length("caplets"."cp_setup_execution"."created_at") > 0),
	CONSTRAINT "cp_setup_execution_updated_at_nonempty_check" CHECK (length("caplets"."cp_setup_execution"."updated_at") > 0),
	CONSTRAINT "cp_setup_execution_aggregate_version_version_check" CHECK ("caplets"."cp_setup_execution"."aggregate_version" >= 0),
	CONSTRAINT "cp_setup_execution_authority_version_version_check" CHECK ("caplets"."cp_setup_execution"."authority_version" >= 0),
	CONSTRAINT "cp_setup_execution_effective_version_version_check" CHECK ("caplets"."cp_setup_execution"."effective_version" >= 0),
	CONSTRAINT "cp_setup_execution_security_version_version_check" CHECK ("caplets"."cp_setup_execution"."security_version" >= 0),
	CONSTRAINT "cp_setup_execution_execution_id_nonempty_check" CHECK (length("caplets"."cp_setup_execution"."execution_id") > 0),
	CONSTRAINT "cp_setup_execution_project_fingerprint_nonempty_check" CHECK (length("caplets"."cp_setup_execution"."project_fingerprint") > 0),
	CONSTRAINT "cp_setup_execution_caplet_id_nonempty_check" CHECK (length("caplets"."cp_setup_execution"."caplet_id") > 0),
	CONSTRAINT "cp_setup_execution_content_hash_nonempty_check" CHECK (length("caplets"."cp_setup_execution"."content_hash") > 0),
	CONSTRAINT "cp_setup_execution_setup_hash_hash_check" CHECK ("caplets"."cp_setup_execution"."setup_hash" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "cp_setup_execution_target_kind_nonempty_check" CHECK (length("caplets"."cp_setup_execution"."target_kind") > 0),
	CONSTRAINT "cp_setup_execution_lease_id_nonempty_check" CHECK (length("caplets"."cp_setup_execution"."lease_id") > 0),
	CONSTRAINT "cp_setup_execution_reserved_at_nonempty_check" CHECK (length("caplets"."cp_setup_execution"."reserved_at") > 0),
	CONSTRAINT "cp_setup_execution_expires_at_nonempty_check" CHECK (length("caplets"."cp_setup_execution"."expires_at") > 0),
	CONSTRAINT "cp_setup_execution_state_nonempty_check" CHECK (length("caplets"."cp_setup_execution"."state") > 0),
	CONSTRAINT "cp_setup_execution_model_version_check" CHECK ("caplets"."cp_setup_execution"."model_version" = 1)
);
--> statement-breakpoint
ALTER TABLE "caplets"."cp_setup_execution" ADD CONSTRAINT "cp_setup_execution_root_fk" FOREIGN KEY ("logical_host_id","store_id") REFERENCES "caplets"."__caplets_storage_identity_v1"("logical_host_id","store_id") ON DELETE restrict ON UPDATE no action;