CREATE TABLE "caplets"."cp_artifact_cleanup_intent" (
	"model_version" bigint NOT NULL,
	"id" text NOT NULL,
	"logical_host_id" text NOT NULL,
	"store_id" text NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL,
	"aggregate_version" bigint NOT NULL,
	"authority_version" bigint NOT NULL,
	"effective_version" bigint NOT NULL,
	"security_version" bigint NOT NULL,
	"cleanup_id" text NOT NULL,
	"artifact_id" text NOT NULL,
	"provider_identity_id" text NOT NULL,
	"inventory_hash" text NOT NULL,
	"state" text NOT NULL,
	"claim_id" text,
	"claim_expires_at" text,
	"receipt" jsonb,
	"completed_at" text,
	CONSTRAINT "cp_artifact_cleanup_intent_pk" PRIMARY KEY("logical_host_id","id"),
	CONSTRAINT "cp_artifact_cleanup_intent_model_version_version_check" CHECK ("caplets"."cp_artifact_cleanup_intent"."model_version" >= 0),
	CONSTRAINT "cp_artifact_cleanup_intent_id_nonempty_check" CHECK (length("caplets"."cp_artifact_cleanup_intent"."id") > 0),
	CONSTRAINT "cp_artifact_cleanup_intent_logical_host_id_nonempty_check" CHECK (length("caplets"."cp_artifact_cleanup_intent"."logical_host_id") > 0),
	CONSTRAINT "cp_artifact_cleanup_intent_store_id_nonempty_check" CHECK (length("caplets"."cp_artifact_cleanup_intent"."store_id") > 0),
	CONSTRAINT "cp_artifact_cleanup_intent_created_at_nonempty_check" CHECK (length("caplets"."cp_artifact_cleanup_intent"."created_at") > 0),
	CONSTRAINT "cp_artifact_cleanup_intent_updated_at_nonempty_check" CHECK (length("caplets"."cp_artifact_cleanup_intent"."updated_at") > 0),
	CONSTRAINT "cp_artifact_cleanup_intent_aggregate_version_version_check" CHECK ("caplets"."cp_artifact_cleanup_intent"."aggregate_version" >= 0),
	CONSTRAINT "cp_artifact_cleanup_intent_authority_version_version_check" CHECK ("caplets"."cp_artifact_cleanup_intent"."authority_version" >= 0),
	CONSTRAINT "cp_artifact_cleanup_intent_effective_version_version_check" CHECK ("caplets"."cp_artifact_cleanup_intent"."effective_version" >= 0),
	CONSTRAINT "cp_artifact_cleanup_intent_security_version_version_check" CHECK ("caplets"."cp_artifact_cleanup_intent"."security_version" >= 0),
	CONSTRAINT "cp_artifact_cleanup_intent_cleanup_id_nonempty_check" CHECK (length("caplets"."cp_artifact_cleanup_intent"."cleanup_id") > 0),
	CONSTRAINT "cp_artifact_cleanup_intent_artifact_id_nonempty_check" CHECK (length("caplets"."cp_artifact_cleanup_intent"."artifact_id") > 0),
	CONSTRAINT "cp_artifact_cleanup_intent_provider_identity_id_hash_check" CHECK ("caplets"."cp_artifact_cleanup_intent"."provider_identity_id" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "cp_artifact_cleanup_intent_inventory_hash_hash_check" CHECK ("caplets"."cp_artifact_cleanup_intent"."inventory_hash" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "cp_artifact_cleanup_intent_state_nonempty_check" CHECK (length("caplets"."cp_artifact_cleanup_intent"."state") > 0),
	CONSTRAINT "cp_artifact_cleanup_intent_claim_id_nonempty_check" CHECK (length("caplets"."cp_artifact_cleanup_intent"."claim_id") > 0),
	CONSTRAINT "cp_artifact_cleanup_intent_claim_expires_at_nonempty_check" CHECK (length("caplets"."cp_artifact_cleanup_intent"."claim_expires_at") > 0),
	CONSTRAINT "cp_artifact_cleanup_intent_completed_at_nonempty_check" CHECK (length("caplets"."cp_artifact_cleanup_intent"."completed_at") > 0),
	CONSTRAINT "cp_artifact_cleanup_intent_model_version_check" CHECK ("caplets"."cp_artifact_cleanup_intent"."model_version" = 1),
	CONSTRAINT "cp_artifact_cleanup_intent_state_check" CHECK ("caplets"."cp_artifact_cleanup_intent"."state" IN ('intended', 'claimed', 'completed', 'failed'))
);
--> statement-breakpoint
CREATE TABLE "caplets"."cp_artifact_manifest" (
	"model_version" bigint NOT NULL,
	"id" text NOT NULL,
	"logical_host_id" text NOT NULL,
	"store_id" text NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL,
	"aggregate_version" bigint NOT NULL,
	"authority_version" bigint NOT NULL,
	"effective_version" bigint NOT NULL,
	"security_version" bigint NOT NULL,
	"artifact_id" text NOT NULL,
	"provider_identity_id" text NOT NULL,
	"logical_key" text NOT NULL,
	"direction" text NOT NULL,
	"actor_id" text NOT NULL,
	"operation_id" text NOT NULL,
	"byte_length" bigint NOT NULL,
	"sha256" text NOT NULL,
	"mime_type" text NOT NULL,
	"part_count" bigint NOT NULL,
	"state" text NOT NULL,
	"expires_at" text NOT NULL,
	"finalized_at" text,
	"destroyed_at" text,
	CONSTRAINT "cp_artifact_manifest_pk" PRIMARY KEY("logical_host_id","id"),
	CONSTRAINT "cp_artifact_manifest_relation_target_uq" UNIQUE("logical_host_id","artifact_id"),
	CONSTRAINT "cp_artifact_manifest_model_version_version_check" CHECK ("caplets"."cp_artifact_manifest"."model_version" >= 0),
	CONSTRAINT "cp_artifact_manifest_id_nonempty_check" CHECK (length("caplets"."cp_artifact_manifest"."id") > 0),
	CONSTRAINT "cp_artifact_manifest_logical_host_id_nonempty_check" CHECK (length("caplets"."cp_artifact_manifest"."logical_host_id") > 0),
	CONSTRAINT "cp_artifact_manifest_store_id_nonempty_check" CHECK (length("caplets"."cp_artifact_manifest"."store_id") > 0),
	CONSTRAINT "cp_artifact_manifest_created_at_nonempty_check" CHECK (length("caplets"."cp_artifact_manifest"."created_at") > 0),
	CONSTRAINT "cp_artifact_manifest_updated_at_nonempty_check" CHECK (length("caplets"."cp_artifact_manifest"."updated_at") > 0),
	CONSTRAINT "cp_artifact_manifest_aggregate_version_version_check" CHECK ("caplets"."cp_artifact_manifest"."aggregate_version" >= 0),
	CONSTRAINT "cp_artifact_manifest_authority_version_version_check" CHECK ("caplets"."cp_artifact_manifest"."authority_version" >= 0),
	CONSTRAINT "cp_artifact_manifest_effective_version_version_check" CHECK ("caplets"."cp_artifact_manifest"."effective_version" >= 0),
	CONSTRAINT "cp_artifact_manifest_security_version_version_check" CHECK ("caplets"."cp_artifact_manifest"."security_version" >= 0),
	CONSTRAINT "cp_artifact_manifest_artifact_id_nonempty_check" CHECK (length("caplets"."cp_artifact_manifest"."artifact_id") > 0),
	CONSTRAINT "cp_artifact_manifest_provider_identity_id_hash_check" CHECK ("caplets"."cp_artifact_manifest"."provider_identity_id" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "cp_artifact_manifest_logical_key_nonempty_check" CHECK (length("caplets"."cp_artifact_manifest"."logical_key") > 0),
	CONSTRAINT "cp_artifact_manifest_direction_nonempty_check" CHECK (length("caplets"."cp_artifact_manifest"."direction") > 0),
	CONSTRAINT "cp_artifact_manifest_actor_id_nonempty_check" CHECK (length("caplets"."cp_artifact_manifest"."actor_id") > 0),
	CONSTRAINT "cp_artifact_manifest_operation_id_nonempty_check" CHECK (length("caplets"."cp_artifact_manifest"."operation_id") > 0),
	CONSTRAINT "cp_artifact_manifest_byte_length_version_check" CHECK ("caplets"."cp_artifact_manifest"."byte_length" >= 0),
	CONSTRAINT "cp_artifact_manifest_sha256_hash_check" CHECK ("caplets"."cp_artifact_manifest"."sha256" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "cp_artifact_manifest_mime_type_nonempty_check" CHECK (length("caplets"."cp_artifact_manifest"."mime_type") > 0),
	CONSTRAINT "cp_artifact_manifest_part_count_version_check" CHECK ("caplets"."cp_artifact_manifest"."part_count" >= 0),
	CONSTRAINT "cp_artifact_manifest_state_nonempty_check" CHECK (length("caplets"."cp_artifact_manifest"."state") > 0),
	CONSTRAINT "cp_artifact_manifest_expires_at_nonempty_check" CHECK (length("caplets"."cp_artifact_manifest"."expires_at") > 0),
	CONSTRAINT "cp_artifact_manifest_finalized_at_nonempty_check" CHECK (length("caplets"."cp_artifact_manifest"."finalized_at") > 0),
	CONSTRAINT "cp_artifact_manifest_destroyed_at_nonempty_check" CHECK (length("caplets"."cp_artifact_manifest"."destroyed_at") > 0),
	CONSTRAINT "cp_artifact_manifest_model_version_check" CHECK ("caplets"."cp_artifact_manifest"."model_version" = 1),
	CONSTRAINT "cp_artifact_manifest_bounds_check" CHECK ("caplets"."cp_artifact_manifest"."byte_length" BETWEEN 1 AND 268435456 AND "caplets"."cp_artifact_manifest"."part_count" BETWEEN 1 AND 256),
	CONSTRAINT "cp_artifact_manifest_direction_check" CHECK ("caplets"."cp_artifact_manifest"."direction" IN ('upload', 'download')),
	CONSTRAINT "cp_artifact_manifest_state_check" CHECK ("caplets"."cp_artifact_manifest"."state" IN ('staging', 'finalized', 'destruction-intended', 'destroyed'))
);
--> statement-breakpoint
CREATE TABLE "caplets"."cp_artifact_part" (
	"model_version" bigint NOT NULL,
	"id" text NOT NULL,
	"logical_host_id" text NOT NULL,
	"store_id" text NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL,
	"aggregate_version" bigint NOT NULL,
	"authority_version" bigint NOT NULL,
	"effective_version" bigint NOT NULL,
	"security_version" bigint NOT NULL,
	"part_id" text NOT NULL,
	"artifact_id" text NOT NULL,
	"ordinal" bigint NOT NULL,
	"object_key" text NOT NULL,
	"offset" bigint NOT NULL,
	"byte_length" bigint NOT NULL,
	"sha256" text NOT NULL,
	"state" text NOT NULL,
	"absent_verified_at" text,
	CONSTRAINT "cp_artifact_part_pk" PRIMARY KEY("logical_host_id","id"),
	CONSTRAINT "cp_artifact_part_model_version_version_check" CHECK ("caplets"."cp_artifact_part"."model_version" >= 0),
	CONSTRAINT "cp_artifact_part_id_nonempty_check" CHECK (length("caplets"."cp_artifact_part"."id") > 0),
	CONSTRAINT "cp_artifact_part_logical_host_id_nonempty_check" CHECK (length("caplets"."cp_artifact_part"."logical_host_id") > 0),
	CONSTRAINT "cp_artifact_part_store_id_nonempty_check" CHECK (length("caplets"."cp_artifact_part"."store_id") > 0),
	CONSTRAINT "cp_artifact_part_created_at_nonempty_check" CHECK (length("caplets"."cp_artifact_part"."created_at") > 0),
	CONSTRAINT "cp_artifact_part_updated_at_nonempty_check" CHECK (length("caplets"."cp_artifact_part"."updated_at") > 0),
	CONSTRAINT "cp_artifact_part_aggregate_version_version_check" CHECK ("caplets"."cp_artifact_part"."aggregate_version" >= 0),
	CONSTRAINT "cp_artifact_part_authority_version_version_check" CHECK ("caplets"."cp_artifact_part"."authority_version" >= 0),
	CONSTRAINT "cp_artifact_part_effective_version_version_check" CHECK ("caplets"."cp_artifact_part"."effective_version" >= 0),
	CONSTRAINT "cp_artifact_part_security_version_version_check" CHECK ("caplets"."cp_artifact_part"."security_version" >= 0),
	CONSTRAINT "cp_artifact_part_part_id_nonempty_check" CHECK (length("caplets"."cp_artifact_part"."part_id") > 0),
	CONSTRAINT "cp_artifact_part_artifact_id_nonempty_check" CHECK (length("caplets"."cp_artifact_part"."artifact_id") > 0),
	CONSTRAINT "cp_artifact_part_ordinal_version_check" CHECK ("caplets"."cp_artifact_part"."ordinal" >= 0),
	CONSTRAINT "cp_artifact_part_object_key_nonempty_check" CHECK (length("caplets"."cp_artifact_part"."object_key") > 0),
	CONSTRAINT "cp_artifact_part_offset_version_check" CHECK ("caplets"."cp_artifact_part"."offset" >= 0),
	CONSTRAINT "cp_artifact_part_byte_length_version_check" CHECK ("caplets"."cp_artifact_part"."byte_length" >= 0),
	CONSTRAINT "cp_artifact_part_sha256_hash_check" CHECK ("caplets"."cp_artifact_part"."sha256" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "cp_artifact_part_state_nonempty_check" CHECK (length("caplets"."cp_artifact_part"."state") > 0),
	CONSTRAINT "cp_artifact_part_absent_verified_at_nonempty_check" CHECK (length("caplets"."cp_artifact_part"."absent_verified_at") > 0),
	CONSTRAINT "cp_artifact_part_model_version_check" CHECK ("caplets"."cp_artifact_part"."model_version" = 1),
	CONSTRAINT "cp_artifact_part_bounds_check" CHECK ("caplets"."cp_artifact_part"."byte_length" BETWEEN 1 AND 16777216),
	CONSTRAINT "cp_artifact_part_state_check" CHECK ("caplets"."cp_artifact_part"."state" IN ('published', 'destruction-intended', 'destroyed'))
);
--> statement-breakpoint
CREATE TABLE "caplets"."cp_artifact_quota_reservation" (
	"model_version" bigint NOT NULL,
	"id" text NOT NULL,
	"logical_host_id" text NOT NULL,
	"store_id" text NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL,
	"aggregate_version" bigint NOT NULL,
	"authority_version" bigint NOT NULL,
	"effective_version" bigint NOT NULL,
	"security_version" bigint NOT NULL,
	"reservation_id" text NOT NULL,
	"actor_id" text NOT NULL,
	"session_id" text NOT NULL,
	"reserved_bytes" bigint NOT NULL,
	"state" text NOT NULL,
	"window_expires_at" text NOT NULL,
	"released_at" text,
	CONSTRAINT "cp_artifact_quota_reservation_pk" PRIMARY KEY("logical_host_id","id"),
	CONSTRAINT "cp_artifact_quota_reservation_model_version_version_check" CHECK ("caplets"."cp_artifact_quota_reservation"."model_version" >= 0),
	CONSTRAINT "cp_artifact_quota_reservation_id_nonempty_check" CHECK (length("caplets"."cp_artifact_quota_reservation"."id") > 0),
	CONSTRAINT "cp_artifact_quota_reservation_logical_host_id_nonempty_check" CHECK (length("caplets"."cp_artifact_quota_reservation"."logical_host_id") > 0),
	CONSTRAINT "cp_artifact_quota_reservation_store_id_nonempty_check" CHECK (length("caplets"."cp_artifact_quota_reservation"."store_id") > 0),
	CONSTRAINT "cp_artifact_quota_reservation_created_at_nonempty_check" CHECK (length("caplets"."cp_artifact_quota_reservation"."created_at") > 0),
	CONSTRAINT "cp_artifact_quota_reservation_updated_at_nonempty_check" CHECK (length("caplets"."cp_artifact_quota_reservation"."updated_at") > 0),
	CONSTRAINT "cp_artifact_quota_reservation_aggregate_version_version_check" CHECK ("caplets"."cp_artifact_quota_reservation"."aggregate_version" >= 0),
	CONSTRAINT "cp_artifact_quota_reservation_authority_version_version_check" CHECK ("caplets"."cp_artifact_quota_reservation"."authority_version" >= 0),
	CONSTRAINT "cp_artifact_quota_reservation_effective_version_version_check" CHECK ("caplets"."cp_artifact_quota_reservation"."effective_version" >= 0),
	CONSTRAINT "cp_artifact_quota_reservation_security_version_version_check" CHECK ("caplets"."cp_artifact_quota_reservation"."security_version" >= 0),
	CONSTRAINT "cp_artifact_quota_reservation_reservation_id_nonempty_check" CHECK (length("caplets"."cp_artifact_quota_reservation"."reservation_id") > 0),
	CONSTRAINT "cp_artifact_quota_reservation_actor_id_nonempty_check" CHECK (length("caplets"."cp_artifact_quota_reservation"."actor_id") > 0),
	CONSTRAINT "cp_artifact_quota_reservation_session_id_nonempty_check" CHECK (length("caplets"."cp_artifact_quota_reservation"."session_id") > 0),
	CONSTRAINT "cp_artifact_quota_reservation_reserved_bytes_version_check" CHECK ("caplets"."cp_artifact_quota_reservation"."reserved_bytes" >= 0),
	CONSTRAINT "cp_artifact_quota_reservation_state_nonempty_check" CHECK (length("caplets"."cp_artifact_quota_reservation"."state") > 0),
	CONSTRAINT "cp_artifact_quota_reservation_window_expires_at_nonempty_check" CHECK (length("caplets"."cp_artifact_quota_reservation"."window_expires_at") > 0),
	CONSTRAINT "cp_artifact_quota_reservation_released_at_nonempty_check" CHECK (length("caplets"."cp_artifact_quota_reservation"."released_at") > 0),
	CONSTRAINT "cp_artifact_quota_reservation_model_version_check" CHECK ("caplets"."cp_artifact_quota_reservation"."model_version" = 1),
	CONSTRAINT "cp_artifact_quota_reservation_state_check" CHECK ("caplets"."cp_artifact_quota_reservation"."state" IN ('reserved', 'destruction-intended', 'released')),
	CONSTRAINT "cp_artifact_quota_reservation_bounds_check" CHECK ("caplets"."cp_artifact_quota_reservation"."reserved_bytes" BETWEEN 1 AND 268435456)
);
--> statement-breakpoint
CREATE TABLE "caplets"."cp_artifact_session" (
	"model_version" bigint NOT NULL,
	"id" text NOT NULL,
	"logical_host_id" text NOT NULL,
	"store_id" text NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL,
	"aggregate_version" bigint NOT NULL,
	"authority_version" bigint NOT NULL,
	"effective_version" bigint NOT NULL,
	"security_version" bigint NOT NULL,
	"session_id" text NOT NULL,
	"artifact_id" text NOT NULL,
	"actor_id" text NOT NULL,
	"operation_id" text NOT NULL,
	"direction" text NOT NULL,
	"state" text NOT NULL,
	"next_offset" bigint NOT NULL,
	"expected_byte_length" bigint NOT NULL,
	"expected_sha256" text NOT NULL,
	"mime_type" text NOT NULL,
	"provider_identity_id" text NOT NULL,
	"expires_at" text NOT NULL,
	"finalized_at" text,
	"revoked_at" text,
	CONSTRAINT "cp_artifact_session_pk" PRIMARY KEY("logical_host_id","id"),
	CONSTRAINT "cp_artifact_session_relation_target_uq" UNIQUE("logical_host_id","session_id"),
	CONSTRAINT "cp_artifact_session_model_version_version_check" CHECK ("caplets"."cp_artifact_session"."model_version" >= 0),
	CONSTRAINT "cp_artifact_session_id_nonempty_check" CHECK (length("caplets"."cp_artifact_session"."id") > 0),
	CONSTRAINT "cp_artifact_session_logical_host_id_nonempty_check" CHECK (length("caplets"."cp_artifact_session"."logical_host_id") > 0),
	CONSTRAINT "cp_artifact_session_store_id_nonempty_check" CHECK (length("caplets"."cp_artifact_session"."store_id") > 0),
	CONSTRAINT "cp_artifact_session_created_at_nonempty_check" CHECK (length("caplets"."cp_artifact_session"."created_at") > 0),
	CONSTRAINT "cp_artifact_session_updated_at_nonempty_check" CHECK (length("caplets"."cp_artifact_session"."updated_at") > 0),
	CONSTRAINT "cp_artifact_session_aggregate_version_version_check" CHECK ("caplets"."cp_artifact_session"."aggregate_version" >= 0),
	CONSTRAINT "cp_artifact_session_authority_version_version_check" CHECK ("caplets"."cp_artifact_session"."authority_version" >= 0),
	CONSTRAINT "cp_artifact_session_effective_version_version_check" CHECK ("caplets"."cp_artifact_session"."effective_version" >= 0),
	CONSTRAINT "cp_artifact_session_security_version_version_check" CHECK ("caplets"."cp_artifact_session"."security_version" >= 0),
	CONSTRAINT "cp_artifact_session_session_id_nonempty_check" CHECK (length("caplets"."cp_artifact_session"."session_id") > 0),
	CONSTRAINT "cp_artifact_session_artifact_id_nonempty_check" CHECK (length("caplets"."cp_artifact_session"."artifact_id") > 0),
	CONSTRAINT "cp_artifact_session_actor_id_nonempty_check" CHECK (length("caplets"."cp_artifact_session"."actor_id") > 0),
	CONSTRAINT "cp_artifact_session_operation_id_nonempty_check" CHECK (length("caplets"."cp_artifact_session"."operation_id") > 0),
	CONSTRAINT "cp_artifact_session_direction_nonempty_check" CHECK (length("caplets"."cp_artifact_session"."direction") > 0),
	CONSTRAINT "cp_artifact_session_state_nonempty_check" CHECK (length("caplets"."cp_artifact_session"."state") > 0),
	CONSTRAINT "cp_artifact_session_next_offset_version_check" CHECK ("caplets"."cp_artifact_session"."next_offset" >= 0),
	CONSTRAINT "cp_artifact_session_expected_byte_length_version_check" CHECK ("caplets"."cp_artifact_session"."expected_byte_length" >= 0),
	CONSTRAINT "cp_artifact_session_expected_sha256_hash_check" CHECK ("caplets"."cp_artifact_session"."expected_sha256" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "cp_artifact_session_mime_type_nonempty_check" CHECK (length("caplets"."cp_artifact_session"."mime_type") > 0),
	CONSTRAINT "cp_artifact_session_provider_identity_id_hash_check" CHECK ("caplets"."cp_artifact_session"."provider_identity_id" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "cp_artifact_session_expires_at_nonempty_check" CHECK (length("caplets"."cp_artifact_session"."expires_at") > 0),
	CONSTRAINT "cp_artifact_session_finalized_at_nonempty_check" CHECK (length("caplets"."cp_artifact_session"."finalized_at") > 0),
	CONSTRAINT "cp_artifact_session_revoked_at_nonempty_check" CHECK (length("caplets"."cp_artifact_session"."revoked_at") > 0),
	CONSTRAINT "cp_artifact_session_model_version_check" CHECK ("caplets"."cp_artifact_session"."model_version" = 1),
	CONSTRAINT "cp_artifact_session_direction_check" CHECK ("caplets"."cp_artifact_session"."direction" IN ('upload', 'download')),
	CONSTRAINT "cp_artifact_session_state_check" CHECK ("caplets"."cp_artifact_session"."state" IN ('uploading', 'finalized', 'consumed', 'revoked', 'expired')),
	CONSTRAINT "cp_artifact_session_bounds_check" CHECK ("caplets"."cp_artifact_session"."expected_byte_length" BETWEEN 1 AND 268435456 AND "caplets"."cp_artifact_session"."next_offset" BETWEEN 0 AND "caplets"."cp_artifact_session"."expected_byte_length")
);
--> statement-breakpoint
CREATE TABLE "caplets"."cp_import_proposal" (
	"model_version" bigint NOT NULL,
	"id" text NOT NULL,
	"logical_host_id" text NOT NULL,
	"store_id" text NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL,
	"aggregate_version" bigint NOT NULL,
	"authority_version" bigint NOT NULL,
	"effective_version" bigint NOT NULL,
	"security_version" bigint NOT NULL,
	"proposal_id" text NOT NULL,
	"artifact_id" text NOT NULL,
	"actor_id" text NOT NULL,
	"operation_id" text NOT NULL,
	"caplet_id" text NOT NULL,
	"proposal_hash" text NOT NULL,
	"expected_authority_generation" bigint NOT NULL,
	"expected_effective_generation" bigint NOT NULL,
	"expected_aggregate_version" bigint NOT NULL,
	"expected_security_epoch" bigint NOT NULL,
	"expected_runtime_fingerprint" text NOT NULL,
	"collision_policy" text NOT NULL,
	"replacement_confirmed" boolean NOT NULL,
	"consequence" text NOT NULL,
	"differences" jsonb NOT NULL,
	"setup_dependencies" jsonb NOT NULL,
	"state" text NOT NULL,
	"expires_at" text NOT NULL,
	"consumed_at" text,
	CONSTRAINT "cp_import_proposal_pk" PRIMARY KEY("logical_host_id","id"),
	CONSTRAINT "cp_import_proposal_model_version_version_check" CHECK ("caplets"."cp_import_proposal"."model_version" >= 0),
	CONSTRAINT "cp_import_proposal_id_nonempty_check" CHECK (length("caplets"."cp_import_proposal"."id") > 0),
	CONSTRAINT "cp_import_proposal_logical_host_id_nonempty_check" CHECK (length("caplets"."cp_import_proposal"."logical_host_id") > 0),
	CONSTRAINT "cp_import_proposal_store_id_nonempty_check" CHECK (length("caplets"."cp_import_proposal"."store_id") > 0),
	CONSTRAINT "cp_import_proposal_created_at_nonempty_check" CHECK (length("caplets"."cp_import_proposal"."created_at") > 0),
	CONSTRAINT "cp_import_proposal_updated_at_nonempty_check" CHECK (length("caplets"."cp_import_proposal"."updated_at") > 0),
	CONSTRAINT "cp_import_proposal_aggregate_version_version_check" CHECK ("caplets"."cp_import_proposal"."aggregate_version" >= 0),
	CONSTRAINT "cp_import_proposal_authority_version_version_check" CHECK ("caplets"."cp_import_proposal"."authority_version" >= 0),
	CONSTRAINT "cp_import_proposal_effective_version_version_check" CHECK ("caplets"."cp_import_proposal"."effective_version" >= 0),
	CONSTRAINT "cp_import_proposal_security_version_version_check" CHECK ("caplets"."cp_import_proposal"."security_version" >= 0),
	CONSTRAINT "cp_import_proposal_proposal_id_nonempty_check" CHECK (length("caplets"."cp_import_proposal"."proposal_id") > 0),
	CONSTRAINT "cp_import_proposal_artifact_id_nonempty_check" CHECK (length("caplets"."cp_import_proposal"."artifact_id") > 0),
	CONSTRAINT "cp_import_proposal_actor_id_nonempty_check" CHECK (length("caplets"."cp_import_proposal"."actor_id") > 0),
	CONSTRAINT "cp_import_proposal_operation_id_nonempty_check" CHECK (length("caplets"."cp_import_proposal"."operation_id") > 0),
	CONSTRAINT "cp_import_proposal_caplet_id_nonempty_check" CHECK (length("caplets"."cp_import_proposal"."caplet_id") > 0),
	CONSTRAINT "cp_import_proposal_proposal_hash_hash_check" CHECK ("caplets"."cp_import_proposal"."proposal_hash" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "cp_import_proposal_expected_authority_generation_version_check" CHECK ("caplets"."cp_import_proposal"."expected_authority_generation" >= 0),
	CONSTRAINT "cp_import_proposal_expected_effective_generation_version_check" CHECK ("caplets"."cp_import_proposal"."expected_effective_generation" >= 0),
	CONSTRAINT "cp_import_proposal_expected_aggregate_version_version_check" CHECK ("caplets"."cp_import_proposal"."expected_aggregate_version" >= 0),
	CONSTRAINT "cp_import_proposal_expected_security_epoch_version_check" CHECK ("caplets"."cp_import_proposal"."expected_security_epoch" >= 0),
	CONSTRAINT "cp_import_proposal_expected_runtime_fingerprint_hash_check" CHECK ("caplets"."cp_import_proposal"."expected_runtime_fingerprint" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "cp_import_proposal_collision_policy_nonempty_check" CHECK (length("caplets"."cp_import_proposal"."collision_policy") > 0),
	CONSTRAINT "cp_import_proposal_consequence_nonempty_check" CHECK (length("caplets"."cp_import_proposal"."consequence") > 0),
	CONSTRAINT "cp_import_proposal_state_nonempty_check" CHECK (length("caplets"."cp_import_proposal"."state") > 0),
	CONSTRAINT "cp_import_proposal_expires_at_nonempty_check" CHECK (length("caplets"."cp_import_proposal"."expires_at") > 0),
	CONSTRAINT "cp_import_proposal_consumed_at_nonempty_check" CHECK (length("caplets"."cp_import_proposal"."consumed_at") > 0),
	CONSTRAINT "cp_import_proposal_model_version_check" CHECK ("caplets"."cp_import_proposal"."model_version" = 1),
	CONSTRAINT "cp_import_proposal_collision_check" CHECK ("caplets"."cp_import_proposal"."collision_policy" IN ('reject', 'replace')),
	CONSTRAINT "cp_import_proposal_state_check" CHECK ("caplets"."cp_import_proposal"."state" IN ('previewed', 'consumed', 'expired', 'rejected'))
);
--> statement-breakpoint
ALTER TABLE "caplets"."cp_artifact_cleanup_intent" ADD CONSTRAINT "cp_artifact_cleanup_intent_root_fk" FOREIGN KEY ("logical_host_id","store_id") REFERENCES "caplets"."__caplets_storage_identity_v1"("logical_host_id","store_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "caplets"."cp_artifact_cleanup_intent" ADD CONSTRAINT "cp_artifact_cleanup_intent_relation_1_fk" FOREIGN KEY ("logical_host_id","artifact_id") REFERENCES "caplets"."cp_artifact_manifest"("logical_host_id","artifact_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "caplets"."cp_artifact_manifest" ADD CONSTRAINT "cp_artifact_manifest_root_fk" FOREIGN KEY ("logical_host_id","store_id") REFERENCES "caplets"."__caplets_storage_identity_v1"("logical_host_id","store_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "caplets"."cp_artifact_part" ADD CONSTRAINT "cp_artifact_part_root_fk" FOREIGN KEY ("logical_host_id","store_id") REFERENCES "caplets"."__caplets_storage_identity_v1"("logical_host_id","store_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "caplets"."cp_artifact_part" ADD CONSTRAINT "cp_artifact_part_relation_1_fk" FOREIGN KEY ("logical_host_id","artifact_id") REFERENCES "caplets"."cp_artifact_manifest"("logical_host_id","artifact_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "caplets"."cp_artifact_quota_reservation" ADD CONSTRAINT "cp_artifact_quota_reservation_root_fk" FOREIGN KEY ("logical_host_id","store_id") REFERENCES "caplets"."__caplets_storage_identity_v1"("logical_host_id","store_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "caplets"."cp_artifact_quota_reservation" ADD CONSTRAINT "cp_artifact_quota_reservation_relation_1_fk" FOREIGN KEY ("logical_host_id","session_id") REFERENCES "caplets"."cp_artifact_session"("logical_host_id","session_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "caplets"."cp_artifact_session" ADD CONSTRAINT "cp_artifact_session_root_fk" FOREIGN KEY ("logical_host_id","store_id") REFERENCES "caplets"."__caplets_storage_identity_v1"("logical_host_id","store_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "caplets"."cp_artifact_session" ADD CONSTRAINT "cp_artifact_session_relation_1_fk" FOREIGN KEY ("logical_host_id","artifact_id") REFERENCES "caplets"."cp_artifact_manifest"("logical_host_id","artifact_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "caplets"."cp_import_proposal" ADD CONSTRAINT "cp_import_proposal_root_fk" FOREIGN KEY ("logical_host_id","store_id") REFERENCES "caplets"."__caplets_storage_identity_v1"("logical_host_id","store_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "caplets"."cp_import_proposal" ADD CONSTRAINT "cp_import_proposal_relation_1_fk" FOREIGN KEY ("logical_host_id","artifact_id") REFERENCES "caplets"."cp_artifact_manifest"("logical_host_id","artifact_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "cp_artifact_cleanup_intent_semantic_uq" ON "caplets"."cp_artifact_cleanup_intent" USING btree ("logical_host_id","cleanup_id");--> statement-breakpoint
CREATE INDEX "cp_artifact_cleanup_intent_query_1_idx" ON "caplets"."cp_artifact_cleanup_intent" USING btree ("logical_host_id","state","claim_expires_at");--> statement-breakpoint
CREATE UNIQUE INDEX "cp_artifact_manifest_semantic_uq" ON "caplets"."cp_artifact_manifest" USING btree ("logical_host_id","artifact_id");--> statement-breakpoint
CREATE INDEX "cp_artifact_manifest_query_1_idx" ON "caplets"."cp_artifact_manifest" USING btree ("logical_host_id","state","expires_at");--> statement-breakpoint
CREATE INDEX "cp_artifact_manifest_query_2_idx" ON "caplets"."cp_artifact_manifest" USING btree ("logical_host_id","actor_id","operation_id");--> statement-breakpoint
CREATE UNIQUE INDEX "cp_artifact_part_semantic_uq" ON "caplets"."cp_artifact_part" USING btree ("logical_host_id","artifact_id","ordinal");--> statement-breakpoint
CREATE INDEX "cp_artifact_part_query_1_idx" ON "caplets"."cp_artifact_part" USING btree ("logical_host_id","artifact_id","ordinal");--> statement-breakpoint
CREATE UNIQUE INDEX "cp_artifact_quota_reservation_semantic_uq" ON "caplets"."cp_artifact_quota_reservation" USING btree ("logical_host_id","reservation_id");--> statement-breakpoint
CREATE INDEX "cp_artifact_quota_reservation_query_1_idx" ON "caplets"."cp_artifact_quota_reservation" USING btree ("logical_host_id","actor_id","state","window_expires_at");--> statement-breakpoint
CREATE INDEX "cp_artifact_quota_reservation_query_2_idx" ON "caplets"."cp_artifact_quota_reservation" USING btree ("logical_host_id","session_id");--> statement-breakpoint
CREATE UNIQUE INDEX "cp_artifact_session_semantic_uq" ON "caplets"."cp_artifact_session" USING btree ("logical_host_id","session_id");--> statement-breakpoint
CREATE INDEX "cp_artifact_session_query_1_idx" ON "caplets"."cp_artifact_session" USING btree ("logical_host_id","actor_id","state","expires_at");--> statement-breakpoint
CREATE INDEX "cp_artifact_session_query_2_idx" ON "caplets"."cp_artifact_session" USING btree ("logical_host_id","operation_id");--> statement-breakpoint
CREATE UNIQUE INDEX "cp_import_proposal_semantic_uq" ON "caplets"."cp_import_proposal" USING btree ("logical_host_id","proposal_id");--> statement-breakpoint
CREATE INDEX "cp_import_proposal_query_1_idx" ON "caplets"."cp_import_proposal" USING btree ("logical_host_id","actor_id","state","expires_at");--> statement-breakpoint
CREATE INDEX "cp_import_proposal_query_2_idx" ON "caplets"."cp_import_proposal" USING btree ("logical_host_id","caplet_id","state");