# syntax=docker/dockerfile:1.7

ARG NODE_VERSION=24-bookworm-slim
ARG PNPM_VERSION=11.9.0

FROM node:${NODE_VERSION} AS build
ARG PNPM_VERSION
ARG CAPLETS_POSTHOG_TOKEN
ARG CAPLETS_RUNTIME_SENTRY_DSN
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@${PNPM_VERSION} --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY apps/catalog/package.json apps/catalog/package.json
COPY apps/docs/package.json apps/docs/package.json
COPY apps/landing/package.json apps/landing/package.json
COPY packages/core/package.json packages/core/package.json
COPY packages/cli/package.json packages/cli/package.json
COPY packages/opencode/package.json packages/opencode/package.json
COPY packages/pi/package.json packages/pi/package.json
COPY packages/benchmarks/package.json packages/benchmarks/package.json
COPY packages/web-observability/package.json packages/web-observability/package.json

RUN pnpm install --frozen-lockfile

COPY . .

RUN node -e "const fs=require('node:fs'); fs.writeFileSync('packages/core/src/telemetry/intake.generated.ts', ['// Generated by Dockerfile build args during image builds.', 'export const BUNDLED_POSTHOG_TOKEN = '+JSON.stringify(process.env.CAPLETS_POSTHOG_TOKEN || undefined)+' as string | undefined;', 'export const BUNDLED_SENTRY_DSN = '+JSON.stringify(process.env.CAPLETS_RUNTIME_SENTRY_DSN || undefined)+' as string | undefined;', ''].join('\\n'))"

RUN pnpm build && pnpm --filter caplets deploy --prod --legacy /deploy

FROM node:${NODE_VERSION} AS runtime
ARG CAPLETS_SENTRY_RELEASE
ARG CAPLETS_SENTRY_ENVIRONMENT=production
ENV NODE_ENV=production \
    XDG_CONFIG_HOME=/data/config \
    XDG_STATE_HOME=/data/state \
    CAPLETS_SERVER_URL=http://127.0.0.1:5387 \
    CAPLETS_REMOTE_SERVER_STATE_DIR=/data/state/caplets/remote-server \
    CAPLETS_SENTRY_RELEASE=${CAPLETS_SENTRY_RELEASE} \
    CAPLETS_SENTRY_ENVIRONMENT=${CAPLETS_SENTRY_ENVIRONMENT}
WORKDIR /app

RUN mkdir -p /data/config /data/state && \
    chown -R node:root /app /data

COPY --from=build --chown=node:root /deploy ./

VOLUME ["/data"]
EXPOSE 5387

USER node

HEALTHCHECK --interval=30s --timeout=5s --retries=5 --start-period=10s \
  CMD node -e "fetch('http://127.0.0.1:5387/v1/healthz').then((response) => process.exit(response.ok ? 0 : 1)).catch(() => process.exit(1))"

CMD ["sh", "-c", "test -f /data/config/caplets/config.json || CAPLETS_MODE=local node dist/index.js init --global && exec env CAPLETS_MODE=local node dist/index.js serve --transport http --host 0.0.0.0"]
