const input = process.env.CAPLETS_OPENAPI_INPUT ?? "./schemas/caplets-http.openapi.json";
const output = process.env.CAPLETS_SDK_OUTPUT ?? "./packages/sdk/src/generated";

export default {
  input,
  output: {
    path: output,
    clean: true,
    entryFile: true,
    header: ({ defaultValue }: { defaultValue: ReadonlyArray<string> }) => [
      "// @ts-nocheck -- generated by pinned HeyAPI; checked through its public entry",
      ...defaultValue,
    ],
    module: {
      extension: null,
    },
  },
  plugins: [
    {
      name: "@hey-api/client-fetch",
      baseUrl: false,
    },
    {
      name: "@hey-api/typescript",
    },
    {
      name: "@hey-api/sdk",
      auth: true,
      client: false,
      responseStyle: "fields",
    },
  ],
};
