packages:
  - "apps/*"
  - "packages/*"
  - "tools/*"

allowBuilds:
  "@google/genai": true
  "@sentry/cli": true
  core-js: true
  esbuild: true
  koffi: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  workerd: true
