import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const page = readFileSync(resolve(__dirname, "../src/pages/index.astro"), "utf8");
const css = readFileSync(resolve(__dirname, "../src/styles/global.css"), "utf8");
const source = `${page}\n${css}`;

const required = [
  "Give your agent Capabilities, not a tool wall",
  "caplets__github",
  "Caplets city map zoom",
  "same capability city",
  "Vanilla MCP",
  "215 tools",
  "7 districts",
  "1 route",
  'shortLabel: "Code Mode"',
  "direct",
  "progressive",
  "code_mode",
  "direct_and_code_mode",
  "progressive_and_code_mode",
  "caplets__{capletId}__{operationName}",
  "caplets__{capletId}",
  "caplets__code_mode",
  "caplets.github",
  "operation: search_tools",
  "GitHub / Context7 / DeepWiki / Playwright / Git / LSP",
  "live Pi eval",
  "Real-world large MCP stack",
  "GitHub, Context7, DeepWiki, Git, filesystem, Playwright, ast-grep, language-server, and web-search",
  "Total Tokens",
  "Tool Surface Tokens",
  "236,803",
  "422,861",
  "461,171",
  "846,048",
  "675,842",
  "124,772",
  "103,776",
  "72.0% fewer",
  "45.5% fewer",
  "31.8% fewer",
  "65.0% fewer",
  "10/10",
  "31,166",
  "215",
  "7",
  "79.9%",
  "Caplets Code Mode",
  "Caplets progressive + Code Mode",
  "Caplets progressive",
  "Direct vanilla MCP",
  "Executor.sh",
  "Exposure modes include direct, progressive, code_mode, direct_and_code_mode, and progressive_and_code_mode.",
  "Remote Caplets server",
  "Auth into tools once. Use them from every agent.",
  "Provider tokens and OAuth state stay with that",
  "Without remote Caplets",
  "With remote Caplets",
  "Each agent client needs its own provider tokens",
  "One server holds provider auth",
  "Auth once on the server",
  "CAPLETS_SERVER_URL=https://caplets.example.com/caplets",
  "CAPLETS_SERVER_PASSWORD=...",
  "caplets serve --transport http",
  "CAPLETS_MODE=remote",
  "opencode",
  "/caplets/v1/mcp",
  "/caplets/v1/admin",
  "/caplets/v1/healthz",
  "remote server command",
  "remote client command",
  "Codex",
  "OpenCode",
  "Pi",
  "caplets setup",
  "Run setup, then add one Caplet.",
  "lets you choose which agent integrations to wire up",
  "caplets install spiritledsoftware/caplets github",
  "caplets install spiritledsoftware/caplets sourcegraph",
  "caplets install spiritledsoftware/caplets osv",
  "caplets auth login sourcegraph",
  "Explore more Caplets",
  "https://github.com/spiritledsoftware/caplets/tree/main/caplets",
  'codex "try using the github caplet"',
  'codex "try using the sourcegraph caplet"',
  'codex "try using the osv caplet"',
  "GH_TOKEN",
  "github",
  "sourcegraph",
  "osv",
  "inspect",
  "search_tools",
  "get_tool",
  "call_tool",
  "data-copy-status",
  'aria-live="polite"',
  "data-copy-label",
  "aria-label={`Copy ${step.label}`}",
  "content={lightThemeColor}",
  "content={darkThemeColor}",
  "color-scheme: light dark;",
  "data-theme-toggle",
  'localStorage.getItem("caplets-theme")',
  ':root[data-theme="dark"]',
  'window.matchMedia("(prefers-color-scheme: dark)")',
  'themeToggle.setAttribute("aria-pressed", String(resolvedTheme === "dark"))',
  'aria-label="Use light theme"',
  "/icon-header-light.png",
  "/icon-header-dark.png",
  'href="#remote"',
  'id="remote"',
  "npm-link",
  "city-zoom",
  "city-stage",
  "city-canvas",
  "city-tab",
  "data-city-zoom",
  "data-city-canvas",
  "data-city-mode",
  "data-city-caption-title",
  "data-city-caption-copy",
  "data-city-caption-meta",
  'import * as THREE from "three"',
  "benchmark-table",
  "benchmark-footnote",
  'type="button"',
  'addEventListener("keydown"',
  'addEventListener("focus"',
  "cityUserPaused",
  'addEventListener("pointerenter"',
  'addEventListener("pointerleave"',
  "data-caplet-examples",
  "data-example-tab",
  "data-example-panel",
  "--radius-control: 8px",
  "--radius-panel: 12px",
  "--radius-shell: 16px",
  "--radius-pill: 999px",
  "border-radius: var(--radius-shell)",
  "border-radius: var(--radius-panel)",
  "border-radius: var(--radius-control)",
];

const forbiddenVisibleCopy = [
  "01</span>",
  "02</span>",
  "03</span>",
  "Try the aha moment",
  "install-step-4",
  "Before: flat tool wall",
  "After: capability first",
  "Exposure prism",
  "trace-reactor",
  "reactor-rail",
  "data-reactor-step",
  "data-reactor-dot",
  "Connect your agent to Caplets.",
  "data-agent-tabs",
  "data-agent-tab",
  "agent-setup-card",
  "agent-setup-panel",
  "integration-pill",
  "Exposure mixer",
  "Exposure compiler",
  "mode-mixer",
  "data-mode-mixer",
  "data-mode-option",
  "data-mode-channels",
  "data-mode-output",
  "data-mode-channel",
  "surface-lab",
  "data-surface-lab",
  "data-surface-option",
  "data-surface-channels",
  "data-surface-readout",
  "data-surface-channel",
  "Trust before invocation",
  "Expanded setup reference",
  "context7",
  "GITHUB_PERSONAL_ACCESS_TOKEN",
  "Docker",
  "plugin marketplace",
  "marketplace add",
  "claude plugin",
  "codex plugin",
  "caplets@caplets",
  "@caplets/opencode",
  "@caplets/pi",
  "plugin installation",
];

const missing = required.filter((needle) => !source.includes(needle));
const forbidden = forbiddenVisibleCopy.filter((needle) => page.includes(needle));

if (missing.length > 0 || forbidden.length > 0) {
  if (missing.length > 0) console.error("Missing required copy:", missing);
  if (forbidden.length > 0) console.error("Forbidden old copy remains:", forbidden);
  process.exit(1);
}

const hardcodedRadii = [...css.matchAll(/border-radius:\s*([^;]+);/g)]
  .map((match) => match[1].trim())
  .filter((value) => !value.startsWith("var(--radius-") && value !== "50%");

if (hardcodedRadii.length > 0) {
  console.error("Hardcoded non-token border radius remains:", hardcodedRadii);
  process.exit(1);
}
