export const REMOTE_CLI_COMMANDS = [
  "list",
  "inspect",
  "check",
  "tools",
  "search_tools",
  "describe_tool",
  "call_tool",
  "resources",
  "search_resources",
  "resource_templates",
  "read_resource",
  "prompts",
  "search_prompts",
  "get_prompt",
  "complete",
  "init",
  "add",
  "install",
  "update",
  "complete_cli",
  "auth_login_start",
  "auth_login_complete",
  "auth_logout",
  "auth_refresh",
  "auth_list",
  "vault_set",
  "vault_list",
  "vault_get",
  "vault_delete",
  "vault_access_grant",
  "vault_access_revoke",
  "vault_access_list",
  "storage_records_list",
  "storage_records_get",
  "storage_records_import",
  "storage_records_update",
  "storage_records_export",
  "storage_records_revisions",
  "storage_records_restore",
  "storage_records_delete_revision",
  "storage_records_retention",
  "storage_records_rename",
  "storage_records_delete",
  "storage_records_installation_status",
  "storage_records_installation_detach",
  "storage_records_installation_observe",
  "storage_records_installation_replace",
] as const;

export type RemoteCliCommand = (typeof REMOTE_CLI_COMMANDS)[number];
export type RemoteCliArguments = Record<string, unknown>;
export type RemoteCliCommandDestination =
  | "admin"
  | "attach"
  | "local_only_rejection"
  | "public_auth_self_service";

export const REMOTE_CLI_COMMAND_DESTINATIONS = {
  list: "attach",
  inspect: "attach",
  check: "attach",
  tools: "attach",
  search_tools: "attach",
  describe_tool: "attach",
  call_tool: "attach",
  resources: "attach",
  search_resources: "attach",
  resource_templates: "attach",
  read_resource: "attach",
  prompts: "attach",
  search_prompts: "attach",
  get_prompt: "attach",
  complete: "attach",
  init: "local_only_rejection",
  add: "local_only_rejection",
  install: "admin",
  update: "admin",
  complete_cli: "attach",
  auth_login_start: "admin",
  auth_login_complete: "public_auth_self_service",
  auth_logout: "admin",
  auth_refresh: "admin",
  auth_list: "admin",
  vault_set: "admin",
  vault_list: "admin",
  vault_get: "admin",
  vault_delete: "admin",
  vault_access_grant: "admin",
  vault_access_revoke: "admin",
  vault_access_list: "admin",
  storage_records_list: "admin",
  storage_records_get: "admin",
  storage_records_import: "admin",
  storage_records_update: "admin",
  storage_records_export: "admin",
  storage_records_revisions: "admin",
  storage_records_restore: "admin",
  storage_records_delete_revision: "admin",
  storage_records_retention: "admin",
  storage_records_rename: "admin",
  storage_records_delete: "admin",
  storage_records_installation_status: "admin",
  storage_records_installation_detach: "admin",
  storage_records_installation_observe: "admin",
  storage_records_installation_replace: "admin",
} as const satisfies Record<RemoteCliCommand, RemoteCliCommandDestination>;
