import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const repoRoot = findRepoRoot(process.cwd());
const docsRoot = join(repoRoot, "apps/docs");
const docsSourceRoot = join(docsRoot, "src");
const docsContentRoot = join(docsSourceRoot, "content/docs");
const generatedMarker =
  "<!-- Generated by scripts/generate-docs-reference.ts. Do not edit by hand. -->";

const requiredPages = [
  "index.mdx",
  "install.mdx",
  "configuration.mdx",
  "code-mode.mdx",
  "capabilities.mdx",
  "agent-integrations.mdx",
  "remote-attach.mdx",
  "troubleshooting.mdx",
  "changelog.mdx",
  "reference/config.mdx",
  "reference/code-mode-api.mdx",
  "reference/caplet-files.mdx",
];

const generatedPages = [
  "changelog.mdx",
  "reference/config.mdx",
  "reference/code-mode-api.mdx",
  "reference/caplet-files.mdx",
];

const requiredContent = new Map<string, string[]>([
  ["index.mdx", ["Code Mode", "npx caplets", "osv"]],
  [
    "install.mdx",
    [
      "npm install -g caplets",
      "npx caplets install spiritledsoftware/caplets osv",
      '"command": "npx"',
    ],
  ],
  ["configuration.mdx", ["https://caplets.dev/config.schema.json", ".caplets/config.json"]],
  [
    "code-mode.mdx",
    ["caplets__code_mode", "caplets.osv.searchTools", "caplets.osv.callTool", "sessionId"],
  ],
  ["capabilities.mdx", ["CAPLET.md", "OpenAPI", "GraphQL", "MCP"]],
  ["agent-integrations.mdx", ["Codex", "Claude", "OpenCode", "Pi"]],
  ["remote-attach.mdx", ["caplets attach", "CAPLETS_MODE=remote"]],
  ["troubleshooting.mdx", ["caplets doctor", "CAPLETS_CONFIG"]],
  ["changelog.mdx", ["Changelog", "GitHub releases"]],
  ["reference/config.mdx", ["https://caplets.dev/config.schema.json", "Required"]],
  ["reference/code-mode-api.mdx", ["CapletHandle", "DebugApi", "CapletsResult"]],
  ["reference/caplet-files.mdx", ["https://caplets.dev/caplet.schema.json", "CAPLET.md"]],
]);

const forbiddenPatterns = [
  "docs/adr",
  "docs/product",
  "docs/plans",
  "docs/specs",
  "/docs/adr",
  "/docs/product",
  "/docs/plans",
  "/docs/specs",
  "github.com/spiritledsoftware/caplets/blob/main/docs/adr",
  "github.com/spiritledsoftware/caplets/blob/main/docs/product",
  "github.com/spiritledsoftware/caplets/blob/main/docs/plans",
  "github.com/spiritledsoftware/caplets/blob/main/docs/specs",
];

const failures: string[] = [];

for (const page of requiredPages) {
  const path = join(docsContentRoot, page);
  if (!existsSync(path)) {
    failures.push(`Missing public docs page: ${relative(repoRoot, path)}`);
    continue;
  }

  const text = readFileSync(path, "utf8");
  const expectedContent = requiredContent.get(page) ?? [];
  for (const expected of expectedContent) {
    if (!text.includes(expected)) {
      failures.push(`${relative(repoRoot, path)} must include ${JSON.stringify(expected)}.`);
    }
  }

  if (generatedPages.includes(page) && !text.includes(generatedMarker)) {
    failures.push(`${relative(repoRoot, path)} is missing the generated marker.`);
  }
}

for (const path of [join(docsRoot, "astro.config.mjs"), ...walkFiles(docsSourceRoot)]) {
  const text = readFileSync(path, "utf8");
  for (const pattern of forbiddenPatterns) {
    if (text.includes(pattern)) {
      failures.push(`${relative(repoRoot, path)} references internal docs path ${pattern}.`);
    }
  }
}

if (failures.length > 0) {
  console.error("Public docs check failed:");
  for (const failure of failures) {
    console.error(`- ${failure}`);
  }
  process.exit(1);
}

function walkFiles(root: string): string[] {
  const files: string[] = [];
  if (!existsSync(root)) return files;

  for (const entry of readdirSync(root)) {
    const path = join(root, entry);
    const stat = statSync(path);
    if (stat.isDirectory()) {
      files.push(...walkFiles(path));
      continue;
    }
    if (stat.isFile() && /\.(astro|css|md|mdx|ts|tsx)$/.test(path)) {
      files.push(path);
    }
  }
  return files;
}

function findRepoRoot(start: string): string {
  let current = resolve(start);
  while (!existsSync(join(current, "pnpm-workspace.yaml"))) {
    const parent = resolve(current, "..");
    if (parent === current) {
      throw new Error(`Could not find repository root from ${start}`);
    }
    current = parent;
  }
  return current;
}
