import { writeFileSync } from "node:fs";

const REQUIRED_TELEMETRY_RELEASE_ENV = [
  {
    name: "CAPLETS_POSTHOG_TOKEN",
    label: "PostHog project token",
    validate: isNonPlaceholderSecret,
  },
  {
    name: "CAPLETS_SENTRY_DSN",
    label: "Sentry DSN",
    validate: isSentryDsn,
  },
] as const;

const BUNDLED_INTAKE_PATH = "packages/core/src/telemetry/intake.generated.ts";

export type TelemetryReleaseEnv = Record<string, string | undefined>;

export function checkTelemetryReleaseEnv(env: TelemetryReleaseEnv): string[] {
  const failures: string[] = [];

  for (const required of REQUIRED_TELEMETRY_RELEASE_ENV) {
    const value = env[required.name];
    if (value === undefined || value.trim() === "") {
      failures.push(`${required.name} is required for telemetry-enabled releases.`);
      continue;
    }
    if (!required.validate(value)) {
      failures.push(
        `${required.name} must be a valid ${required.label}; placeholders are not allowed.`,
      );
    }
  }

  return failures;
}

export function writeBundledTelemetryIntake(env: TelemetryReleaseEnv): void {
  const posthogToken = env.CAPLETS_POSTHOG_TOKEN;
  const sentryDsn = env.CAPLETS_SENTRY_DSN;
  writeFileSync(
    BUNDLED_INTAKE_PATH,
    [
      "// Generated by scripts/check-telemetry-release-env.ts during release builds.",
      `export const BUNDLED_POSTHOG_TOKEN = ${JSON.stringify(posthogToken)} as string | undefined;`,
      `export const BUNDLED_SENTRY_DSN = ${JSON.stringify(sentryDsn)} as string | undefined;`,
      "",
    ].join("\n"),
  );
}

function isNonPlaceholderSecret(value: string): boolean {
  const normalized = value.trim().toLowerCase();
  if (normalized === "") return false;
  return ![
    "todo",
    "todo before release",
    "changeme",
    "change-me",
    "placeholder",
    "example",
  ].includes(normalized);
}

function isSentryDsn(value: string): boolean {
  if (!isNonPlaceholderSecret(value)) return false;

  try {
    const url = new URL(value);
    return (
      (url.protocol === "https:" || url.protocol === "http:") &&
      url.username.length > 0 &&
      url.hostname.length > 0 &&
      url.pathname !== "" &&
      url.pathname !== "/"
    );
  } catch {
    return false;
  }
}

if (import.meta.url === new URL(process.argv[1] ?? "", "file:").href) {
  const failures = checkTelemetryReleaseEnv(process.env);
  if (failures.length > 0) {
    console.error("Telemetry release environment is not configured:");
    for (const failure of failures) {
      console.error(`- ${failure}`);
    }
    console.error(
      "Configure GitHub Actions secrets CAPLETS_POSTHOG_TOKEN and CAPLETS_SENTRY_DSN before publishing.",
    );
    process.exit(1);
  }

  if (process.argv.includes("--write-bundled-intake")) {
    writeBundledTelemetryIntake(process.env);
    console.log(`Wrote bundled telemetry intake identifiers to ${BUNDLED_INTAKE_PATH}.`);
  }

  console.log("Telemetry release environment is configured.");
}
