import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";

type JsonSchema = {
  title?: string;
  description?: string;
  type?: string | string[];
  required?: string[];
  properties?: Record<string, JsonSchema>;
  items?: JsonSchema;
  enum?: unknown[];
  oneOf?: JsonSchema[];
  anyOf?: JsonSchema[];
  allOf?: JsonSchema[];
  additionalProperties?: boolean | JsonSchema;
  $ref?: string;
};

const repoRoot = findRepoRoot(process.cwd());
const generatedMarker =
  "<!-- Generated by scripts/generate-docs-reference.ts. Do not edit by hand. -->";
const generatedMarkerComment = `{/* ${generatedMarker} */}`;
const fallbackFieldDescriptions = new Map<string, string>([
  ["actions", "Configured actions keyed by stable tool name."],
  ["cacheTtlMs", "Milliseconds successful discovery results stay fresh."],
  ["commands", "Setup commands users can run before using this Caplet."],
  ["defaultSearchLimit", "Default number of search results returned when no limit is provided."],
  ["discoveryTimeoutMs", "Timeout in milliseconds for downstream discovery checks."],
  ["env", "Environment variables added when the command runs."],
  [
    "exposureDiscoveryConcurrency",
    "Maximum number of Caplets inspected concurrently during exposure discovery.",
  ],
  ["exposureDiscoveryTimeoutMs", "Timeout in milliseconds for exposure discovery."],
  ["features", "Runtime features this Caplet expects from the host."],
  ["maxOutputBytes", "Maximum combined stdout and stderr bytes to keep."],
  ["maxSearchLimit", "Maximum accepted search result limit."],
  ["negativeCacheTtlMs", "Milliseconds failed discovery results stay cached."],
  ["overallTimeoutMs", "Overall timeout in milliseconds for completion discovery."],
  ["resources", "Hosted resource requirements for this Caplet."],
  ["required", "Whether this capability requires the declared runtime feature or binding."],
  ["setup", "Optional setup and verification metadata."],
  ["tags", "Optional tags for grouping or searching Caplets."],
  ["timeoutMs", "Timeout in milliseconds."],
  ["toolCacheTtlMs", "Milliseconds tool metadata stays fresh."],
  ["verify", "Verification commands users can run to check setup."],
]);

const outputs = new Map<string, string>([
  [
    "apps/docs/src/content/docs/reference/config.mdx",
    formatMdx(
      schemaPage({
        title: "Configuration schema",
        description: "Generated reference for `caplets.json` and `.caplets/config.json`.",
        sourcePath: "schemas/caplets-config.schema.json",
        canonicalUrl: "https://caplets.dev/config.schema.json",
        intro:
          "Use this page to scan the public Caplets configuration shape. The linked JSON Schema remains the canonical editor integration target.",
      }),
    ),
  ],
  [
    "apps/docs/src/content/docs/reference/caplet-files.mdx",
    formatMdx(
      schemaPage({
        title: "Caplet files",
        description: "Generated reference for Markdown Caplet file frontmatter.",
        sourcePath: "schemas/caplet.schema.json",
        canonicalUrl: "https://caplets.dev/caplet.schema.json",
        intro:
          "Caplet files are Markdown files with YAML frontmatter. Store a single-file Caplet as `osv.md`, or use a folder with `CAPLET.md` when the capability needs nearby assets.",
      }),
    ),
  ],
  ["apps/docs/src/content/docs/reference/code-mode-api.mdx", formatMdx(codeModeApiPage())],
]);

if (process.argv.includes("--check")) {
  const stale = Array.from(outputs).filter(([path, next]) => {
    const absolutePath = join(repoRoot, path);
    return !existsSync(absolutePath) || readFileSync(absolutePath, "utf8") !== next;
  });

  if (stale.length > 0) {
    console.error("Public docs reference files are out of date. Run pnpm docs:generate.");
    for (const [path] of stale) {
      console.error(`- ${path}`);
    }
    process.exit(1);
  }
} else {
  for (const [path, text] of outputs) {
    const absolutePath = join(repoRoot, path);
    mkdirSync(dirname(absolutePath), { recursive: true });
    writeFileSync(absolutePath, text);
    console.log(`Generated ${relative(repoRoot, absolutePath)}`);
  }
}

function schemaPage({
  title,
  description,
  sourcePath,
  canonicalUrl,
  intro,
}: {
  title: string;
  description: string;
  sourcePath: string;
  canonicalUrl: string;
  intro: string;
}): string {
  const schema = readJsonSchema(sourcePath);
  const required = new Set(schema.required ?? []);
  const rows = Object.entries(schema.properties ?? {}).map(([name, property]) => ({
    name,
    status: required.has(name) ? "Required" : "Optional",
    type: schemaType(property),
    description: fieldDescription(name, property),
  }));

  const majorSections = rows.filter(({ name }) =>
    [
      "completion",
      "options",
      "mcpServers",
      "openapiEndpoints",
      "googleDiscoveryApis",
      "graphqlEndpoints",
      "httpApis",
      "cliTools",
      "capletSets",
      "setup",
      "projectBinding",
      "runtime",
      "mcpServer",
      "openapiEndpoint",
      "googleDiscoveryApi",
      "graphqlEndpoint",
      "httpApi",
      "capletSet",
    ].includes(name),
  );

  return `${frontmatter(title, description)}
${generatedMarkerComment}

${intro}

Canonical schema: [${canonicalUrl}](${canonicalUrl})

Status values are \`Required\` or \`Optional\` according to the schema's top-level \`required\` array.

${commonSchemaRecipes(sourcePath)}

## Top-level fields

| Field | Status | Type | Description |
| --- | --- | --- | --- |
${rows.map((row) => `| \`${escapeTable(row.name)}\` | ${row.status} | ${escapeTable(row.type)} | ${escapeTable(row.description)} |`).join("\n")}

## Major sections

${majorSections.map((row) => sectionDetails(row.name, schema.properties?.[row.name], sourcePath)).join("\n\n")}
`;
}

function sectionDetails(name: string, schema: JsonSchema | undefined, sourcePath: string): string {
  if (!schema) return `### \`${name}\`\n\nNo generated details are available.`;
  if (sourcePath === "schemas/caplet.schema.json" && name === "cliTools") {
    return cliToolsCapletFileSection(schema);
  }

  const nested =
    schema.properties ??
    schema.items?.properties ??
    (typeof schema.additionalProperties === "object"
      ? schema.additionalProperties.properties
      : undefined);
  if (!nested) {
    return `### \`${name}\`\n\n${schema.description ?? "See the canonical schema for the full nested shape."}`;
  }

  const required = new Set(
    schema.required ??
      schema.items?.required ??
      (typeof schema.additionalProperties === "object"
        ? schema.additionalProperties.required
        : undefined) ??
      [],
  );
  const rows = Object.entries(nested).map(([field, property]) => {
    const status = required.has(field) ? "Required" : "Optional";
    const description = fieldDescription(field, property);
    return `| \`${escapeTable(field)}\` | ${status} | ${escapeTable(schemaType(property))} | ${escapeTable(description)} |`;
  });

  return `### \`${name}\`

${schema.description ?? "Nested fields from the canonical schema."}

| Field | Status | Type | Description |
| --- | --- | --- | --- |
${rows.join("\n")}`;
}

function cliToolsCapletFileSection(schema: JsonSchema): string {
  return `### \`cliTools\`

${schema.description ?? "CLI tools backend configuration, or plural CLI backend configurations."}

Singular form:

| Field | Status | Type | Description |
| --- | --- | --- | --- |
| \`actions\` | Required | object | Configured CLI actions keyed by stable tool name. |
| \`disabled\` | Optional | boolean | When true, omit this Caplet from discovery. |
| \`projectBinding\` | Optional | object | Project Binding requirements for Caplets that need an attached project. |
| \`runtime\` | Optional | object | Runtime feature and resource requirements for hosted execution. |

Plural form child fields:

| Field | Status | Type | Description |
| --- | --- | --- | --- |
| \`actions\` | Required | object | Configured CLI actions keyed by stable tool name. |
| \`disabled\` | Optional | boolean | When true, omit this Caplet from discovery. |
| \`projectBinding\` | Optional | object | Project Binding requirements for Caplets that need an attached project. |
| \`runtime\` | Optional | object | Runtime feature and resource requirements for hosted execution. |
| \`name\` | Optional | string | See the canonical schema for details. |
| \`description\` | Optional | string | See the canonical schema for details. |
| \`tags\` | Optional | array | Optional tags for grouping or searching Caplets. |
| \`exposure\` | Optional | "direct" \\| "progressive" \\| "code_mode" \\| "direct_and_code_mode" \\| "progressive_and_code_mode" | How this Caplet is exposed to agents. |
| \`shadowing\` | Optional | "forbid" \\| "allow" \\| "namespace" | Whether attached local Caplets may shadow this remote Caplet ID. |
| \`useWhen\` | Optional | string | When agents should prefer this Caplet or configured action. |
| \`avoidWhen\` | Optional | string | When agents should avoid this Caplet or configured action. |
| \`setup\` | Optional | object | Optional explicit setup and verification metadata for this Caplet. |

Plural \`cliTools\` is recognized only when the value is a child-ID map. \`actions\` is reserved for the singular form and cannot be used as a plural child ID.`;
}

function commonSchemaRecipes(sourcePath: string): string {
  if (sourcePath === "schemas/caplets-config.schema.json") {
    return [
      "## Common config",
      "",
      "Minimal user config:",
      "",
      "```json",
      "{",
      '  "$schema": "https://caplets.dev/config.schema.json",',
      '  "mcpServers": {}',
      "}",
      "```",
      "",
      "Keep `options.exposure` at the default `code_mode` unless your client cannot run Code",
      "Mode. Add backend maps such as `mcpServers`, `openapiEndpoints`,",
      "`googleDiscoveryApis`, `graphqlEndpoints`, `httpApis`, `cliTools`, or `capletSets` only",
      "for the capability sources you actually want agents to see.",
      "",
      "Stdio MCP server:",
      "",
      "```json",
      "{",
      '  "$schema": "https://caplets.dev/config.schema.json",',
      '  "mcpServers": {',
      '    "github": {',
      '      "name": "GitHub",',
      '      "description": "Inspect repositories, issues, pull requests, and workflow runs.",',
      '      "command": "github-mcp-server",',
      '      "args": ["stdio"]',
      "    }",
      "  }",
      "}",
      "```",
      "",
      "Public OpenAPI endpoint:",
      "",
      "```json",
      "{",
      '  "$schema": "https://caplets.dev/config.schema.json",',
      '  "openapiEndpoints": {',
      '    "status-api": {',
      '      "name": "Status API",',
      '      "description": "Read public service health from the status API.",',
      '      "specUrl": "https://api.example.com/openapi.json",',
      '      "baseUrl": "https://api.example.com",',
      '      "auth": { "type": "none" }',
      "    }",
      "  }",
      "}",
      "```",
    ].join("\n");
  }

  if (sourcePath === "schemas/caplet.schema.json") {
    return [
      "## Common frontmatter",
      "",
      "Minimal Markdown Caplet:",
      "",
      "```md",
      "---",
      "name: Example Tools",
      "description: Expose a small local MCP server to agents.",
      "exposure: code_mode",
      "mcpServer:",
      "  command: npx",
      '  args: ["-y", "@modelcontextprotocol/server-everything"]',
      "---",
      "",
      "Use this Caplet when an agent needs the example MCP tools.",
      "```",
      "",
      "Use `useWhen` and `avoidWhen` to guide agent selection, and add `setup` metadata when a",
      "Caplet needs local commands before it can run.",
      "",
      "Project-bound Caplet with setup:",
      "",
      "```md",
      "---",
      "name: Repository Checks",
      "description: Run repository-local checks before an agent edits this project.",
      "exposure: code_mode",
      "cliTools:",
      "  actions:",
      "    test:",
      "      description: Run the project test suite.",
      "      command: pnpm",
      '      args: ["test"]',
      "projectBinding:",
      "  required: true",
      "setup:",
      "  verify:",
      "    - label: Test suite",
      "      command: pnpm",
      '      args: ["test"]',
      "---",
      "",
      "Use this Caplet when an agent needs the current repository's local test signal.",
      "```",
      "",
      "Provider suite with multiple runtime children:",
      "",
      "```md",
      "---",
      "name: Google Workspace",
      "description: Work with Gmail and Drive from one installable capability.",
      "tags: [google, workspace]",
      "auth:",
      "  type: oauth2",
      "  issuer: https://accounts.google.com",
      "googleDiscoveryApis:",
      "  drive:",
      "    name: Google Drive",
      "    description: Search and inspect Drive files.",
      "    discoveryPath: ./drive.discovery.json",
      "    includeOperations: [drive.files.list, drive.files.get]",
      "    auth:",
      "      type: oauth2",
      "      issuer: https://accounts.google.com",
      "      scopes:",
      "        - https://www.googleapis.com/auth/drive.metadata.readonly",
      "  gmail:",
      "    name: Gmail",
      "    description: Search and inspect Gmail messages.",
      "    discoveryPath: ./gmail.discovery.json",
      "    includeOperations: [gmail.users.messages.list, gmail.users.messages.get]",
      "    auth:",
      "      type: oauth2",
      "      issuer: https://accounts.google.com",
      "      scopes:",
      "        - https://www.googleapis.com/auth/gmail.readonly",
      "---",
      "",
      "Use this Caplet when an agent needs Workspace context across mail and files.",
      "```",
      "",
      "Installing the parent `google-workspace` copies the whole suite. Runtime handles are",
      "`google-workspace__drive` and `google-workspace__gmail`; child IDs are not installed",
      "directly. Use plural backend maps for one authored provider suite, and use `capletSet`",
      "or `capletSets` only when composing or nesting another Caplets collection.",
    ].join("\n");
  }

  return "";
}

function codeModeApiRecipes(): string {
  return [
    "## Common Code Mode recipes",
    "",
    "Guard against unavailable backends before you spend work on discovery:",
    "",
    "```ts",
    "const h = caplets.osv;",
    "const ready = await h.check();",
    "if (!ready.ok) {",
    "  return { ok: false, reason: ready.error.message };",
    "}",
    "```",
    "",
    "Discover, describe, and call the best matching tool:",
    "",
    "```ts",
    "const h = caplets.osv;",
    'const tools = await h.searchTools("package version", { limit: 5 });',
    "const tool = tools.items[0];",
    'if (!tool) return { ok: false, reason: "No matching tool" };',
    "",
    "const details = await h.describeTool(tool.name);",
    "const result = await h.callTool(tool.name, {",
    '  ecosystem: "npm",',
    '  name: "react",',
    '  version: "18.2.0",',
    "});",
    "",
    "return {",
    "  tool: tool.name,",
    "  callOk: result.ok,",
    "  evidence: result.ok ? result.data : result.error.message,",
    "  schemaKnown: details.ok,",
    "};",
    "```",
    "",
    "Page through larger result sets with `nextCursor`:",
    "",
    "```ts",
    "const h = caplets.github;",
    "const repos = [];",
    "let cursor: string | undefined;",
    "do {",
    "  const page = await h.tools({ limit: 25, cursor });",
    "  repos.push(...page.items.map((item) => item.name));",
    "  cursor = page.nextCursor;",
    "} while (cursor && repos.length < 100);",
    "",
    "return { count: repos.length, repos };",
    "```",
    "",
    "Use resources and prompts when a Caplet exposes reusable context:",
    "",
    "```ts",
    "const h = caplets.docs;",
    'const resources = await h.searchResources("configuration", { limit: 3 });',
    "const first = resources.items[0];",
    "const content = first?.uri ? await h.readResource(first.uri) : undefined;",
    "",
    'const prompts = await h.searchPrompts("review", { limit: 3 });',
    "",
    "return {",
    "  resources: resources.items.map((item) => item.uri),",
    "  firstResourceOk: content?.ok ?? false,",
    "  prompts: prompts.items.map((item) => item.name),",
    "};",
    "```",
    "",
    "Reuse a live session only when the calling client passes the `sessionId` returned in",
    "`meta.sessionId` from a successful fresh or reused run. Unknown or expired sessions fail",
    "before submitted code runs, and heap state is not durable across process restarts or TTL",
    "eviction.",
    "",
    "Read recovery history only with a `recoveryRef` that was already returned when the session",
    "was created:",
    "",
    "```ts",
    "const history = await caplets.debug.readRecovery({",
    '  recoveryRef: "code-mode-recovery-ref",',
    "  limit: 20,",
    "});",
    "",
    "return {",
    "  nextCursor: history.nextCursor,",
    "  setupCandidates: history.entries",
    '    .filter((entry) => entry.recoveryClassification === "setup_like")',
    "    .map((entry) => ({ summary: entry.summary, ok: entry.outcome.ok })),",
    "};",
    "```",
    "",
    "Recovery returns redacted, bounded summaries for reconstructing setup code manually. It does",
    "not restore heap, closures, timers, promises, or host handles, and a stale `sessionId` does",
    "not grant a recovery ref.",
    "",
    "Read execution logs through the generated debug handle when a Caplet returns a log ref:",
    "",
    "```ts",
    "const result = await caplets.debug.readLogs({",
    '  logRef: "caplet-run-log-ref",',
    "  limit: 100,",
    "});",
    "",
    "return {",
    "  nextCursor: result.nextCursor,",
    '  errors: result.entries.filter((entry) => entry.level === "error"),',
    "};",
    "```",
  ].join("\n");
}

function codeModeApiPage(): string {
  const source = readFileSync(
    join(repoRoot, "packages/core/src/code-mode/runtime-api.d.ts"),
    "utf8",
  );
  const blocks = [
    "type JsonPrimitive",
    "type JsonValue",
    "interface CapletHandle",
    "interface DebugApi",
    "type CapletCard",
    "type PageInput",
    "type Page",
    "type CapletsResult",
    "type CapletsMeta",
    "type CapletsError",
    "type BackendCheckResult",
    "type ToolSummary",
    "type ToolDescriptor",
    "type ObservedOutputShape",
    "type JsonShape",
    "type ResourceSummary",
    "type ResourceTemplateSummary",
    "type ResourceReadResult",
    "type PromptSummary",
    "type PromptResult",
    "type CompleteInput",
    "type CompleteResult",
    "type ReadLogsInput",
    "type ReadLogsResult",
    "type ReadCodeModeRecoveryInput",
    "type CodeModeDiagnostic",
    "type CodeModeRecoveryClassification",
    "type CodeModeRecoveryEntry",
    "type ReadCodeModeRecoveryResult",
    "type CodeModeLogEntry",
    "type CodeModeSessionStatus",
    "type CodeModeRunMeta",
  ]
    .map((name) => extractDeclaration(source, name))
    .filter((block): block is string => Boolean(block));

  return `${frontmatter("Code Mode API", "Generated reference for the lean TypeScript handle surface available inside `caplets__code_mode`.")}
${generatedMarkerComment}

Code Mode runs TypeScript with generated \`caplets.<id>\` handles. Prefer discovery methods first, then call downstream tools with compact, decision-ready inputs and outputs.

This reference intentionally lists the lean generated declaration surface: Caplet handles, debug helpers, shared result types, and \`console\`. Runtime platform globals such as \`URL\`, \`TextEncoder\`, \`Headers\`, timers, and \`crypto.randomUUID()\` are available for ordinary JavaScript data shaping, but they are not enumerated here or in the Code Mode tool prompt.

${codeModeApiRecipes()}

## Runtime handles

${blocks.map((block) => `\`\`\`ts\n${block}\n\`\`\``).join("\n\n")}
`;
}

function extractDeclaration(source: string, declaration: string): string | undefined {
  const match = new RegExp(`(^|\\n)${escapeRegExp(declaration)}(?=[<\\s=])`).exec(source);
  if (!match) return undefined;
  const start = match.index + (match[1] ? match[1].length : 0);
  const lineEnd = source.indexOf("\n", start);
  const declarationLine = source.slice(start, lineEnd === -1 ? undefined : lineEnd);
  if (!declarationLine.includes("{")) {
    if (declarationLine.trimEnd().endsWith(";")) {
      return declarationLine.trim();
    }
    const nextDeclaration = /\n(?:interface|type)\s+[A-Za-z_$]/u.exec(source.slice(lineEnd + 1));
    const end = nextDeclaration ? lineEnd + 1 + nextDeclaration.index : source.length;
    return source.slice(start, end).trim();
  }

  let index = start;
  let depth = 0;
  let seenBrace = false;
  while (index < source.length) {
    const char = source[index];
    if (char === "{") {
      depth++;
      seenBrace = true;
    } else if (char === "}") {
      depth--;
      if (seenBrace && depth === 0) {
        const semicolon = source[index + 1] === ";" ? index + 2 : index + 1;
        return source.slice(start, semicolon).trim();
      }
    }
    index++;
  }

  return undefined;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function schemaType(schema: JsonSchema): string {
  if (schema.$ref) return schema.$ref.split("/").at(-1) ?? schema.$ref;
  if (schema.enum) return schema.enum.map((value) => JSON.stringify(value)).join(" | ");
  if (schema.type) return Array.isArray(schema.type) ? schema.type.join(" | ") : schema.type;
  if (schema.oneOf) return uniqueTypes(schema.oneOf, " | ");
  if (schema.anyOf) return uniqueTypes(schema.anyOf, " | ");
  if (schema.allOf) return uniqueTypes(schema.allOf, " & ");
  if (schema.additionalProperties && typeof schema.additionalProperties === "object") {
    return `record of ${schemaType(schema.additionalProperties)}`;
  }
  if (schema.properties) return "object";
  if (schema.items) return `${schemaType(schema.items)}[]`;
  return "unknown";
}

function uniqueTypes(schemas: JsonSchema[], separator: string): string {
  return Array.from(new Set(schemas.map(schemaType))).join(separator);
}

function fieldDescription(field: string, schema: JsonSchema): string {
  if (schema.description) return schema.description;
  return (
    fallbackFieldDescriptions.get(field) ??
    (schema.type === "array"
      ? `Optional list of ${field}.`
      : "See the canonical schema for details.")
  );
}

function readJsonSchema(path: string): JsonSchema {
  return JSON.parse(readFileSync(join(repoRoot, path), "utf8")) as JsonSchema;
}

function frontmatter(title: string, description: string): string {
  return `---\ntitle: ${JSON.stringify(title)}\ndescription: ${JSON.stringify(description)}\n---\n`;
}

function escapeTable(value: string): string {
  return value
    .replaceAll("|", "\\|")
    .replaceAll("{", "\\{")
    .replaceAll("}", "\\}")
    .replaceAll("\n", " ");
}

function formatMdx(value: string): string {
  const dir = mkdtempSync(join(tmpdir(), "caplets-docs-"));
  const path = join(dir, "page.mdx");
  try {
    writeFileSync(path, value);
    execFileSync("pnpm", ["exec", "oxfmt", path], { stdio: "inherit" });
    return readFileSync(path, "utf8");
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function findRepoRoot(start: string): string {
  let current = resolve(start);
  while (!existsSync(join(current, "pnpm-workspace.yaml"))) {
    const parent = dirname(current);
    if (parent === current) {
      throw new Error(`Could not find repository root from ${start}`);
    }
    current = parent;
  }
  return current;
}
