import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";

type JsonSchema = {
  title?: string;
  description?: string;
  type?: string | string[];
  required?: string[];
  properties?: Record<string, JsonSchema>;
  items?: JsonSchema;
  enum?: unknown[];
  oneOf?: JsonSchema[];
  anyOf?: JsonSchema[];
  allOf?: JsonSchema[];
  additionalProperties?: boolean | JsonSchema;
  $ref?: string;
};

const repoRoot = findRepoRoot(process.cwd());
const generatedMarker =
  "<!-- Generated by scripts/generate-docs-reference.ts. Do not edit by hand. -->";
const generatedMarkerComment = `{/* ${generatedMarker} */}`;

const outputs = new Map<string, string>([
  [
    "apps/docs/src/content/docs/reference/config.mdx",
    formatMdx(
      schemaPage({
        title: "Configuration schema",
        description: "Generated reference for `caplets.json` and `.caplets/config.json`.",
        sourcePath: "schemas/caplets-config.schema.json",
        canonicalUrl: "https://caplets.dev/config.schema.json",
        intro:
          "Use this page to scan the public Caplets configuration shape. The linked JSON Schema remains the canonical editor integration target.",
      }),
    ),
  ],
  [
    "apps/docs/src/content/docs/reference/caplet-files.mdx",
    formatMdx(
      schemaPage({
        title: "Caplet files",
        description: "Generated reference for Markdown Caplet file frontmatter.",
        sourcePath: "schemas/caplet.schema.json",
        canonicalUrl: "https://caplets.dev/caplet-frontmatter.schema.json",
        intro:
          "Caplet files are Markdown files with YAML frontmatter. Store a single-file Caplet as `osv.md`, or use a folder with `CAPLET.md` when the capability needs nearby assets.",
      }),
    ),
  ],
  ["apps/docs/src/content/docs/reference/code-mode-api.mdx", formatMdx(codeModeApiPage())],
  ["apps/docs/src/content/docs/changelog.mdx", formatMdx(changelogPage())],
]);

if (process.argv.includes("--check")) {
  const stale = Array.from(outputs).filter(([path, next]) => {
    const absolutePath = join(repoRoot, path);
    return !existsSync(absolutePath) || readFileSync(absolutePath, "utf8") !== next;
  });

  if (stale.length > 0) {
    console.error("Public docs reference files are out of date. Run pnpm docs:generate.");
    for (const [path] of stale) {
      console.error(`- ${path}`);
    }
    process.exit(1);
  }
} else {
  for (const [path, text] of outputs) {
    const absolutePath = join(repoRoot, path);
    mkdirSync(dirname(absolutePath), { recursive: true });
    writeFileSync(absolutePath, text);
    console.log(`Generated ${relative(repoRoot, absolutePath)}`);
  }
}

function schemaPage({
  title,
  description,
  sourcePath,
  canonicalUrl,
  intro,
}: {
  title: string;
  description: string;
  sourcePath: string;
  canonicalUrl: string;
  intro: string;
}): string {
  const schema = readJsonSchema(sourcePath);
  const required = new Set(schema.required ?? []);
  const rows = Object.entries(schema.properties ?? {}).map(([name, property]) => ({
    name,
    status: required.has(name) ? "Required" : "Optional",
    type: schemaType(property),
    description: property.description ?? "",
  }));

  const majorSections = rows.filter(({ name }) =>
    [
      "completion",
      "options",
      "mcpServers",
      "openapiEndpoints",
      "graphqlEndpoints",
      "httpApis",
      "cliTools",
      "capletSets",
      "setup",
      "projectBinding",
      "runtime",
      "mcpServer",
      "openapiEndpoint",
      "graphqlEndpoint",
      "httpApi",
      "capletSet",
    ].includes(name),
  );

  return `${frontmatter(title, description)}
${generatedMarkerComment}

${intro}

Canonical schema: [${canonicalUrl}](${canonicalUrl})

Status values are \`Required\` or \`Optional\` according to the schema's top-level \`required\` array.

## Top-level fields

| Field | Status | Type | Description |
| --- | --- | --- | --- |
${rows.map((row) => `| \`${escapeTable(row.name)}\` | ${row.status} | ${escapeTable(row.type)} | ${escapeTable(row.description)} |`).join("\n")}

## Major sections

${majorSections.map((row) => sectionDetails(row.name, schema.properties?.[row.name])).join("\n\n")}
`;
}

function sectionDetails(name: string, schema: JsonSchema | undefined): string {
  if (!schema) return `### \`${name}\`\n\nNo generated details are available.`;

  const nested =
    schema.properties ??
    schema.items?.properties ??
    (typeof schema.additionalProperties === "object"
      ? schema.additionalProperties.properties
      : undefined);
  if (!nested) {
    return `### \`${name}\`\n\n${schema.description ?? "See the canonical schema for the full nested shape."}`;
  }

  const required = new Set(
    schema.required ??
      schema.items?.required ??
      (typeof schema.additionalProperties === "object"
        ? schema.additionalProperties.required
        : undefined) ??
      [],
  );
  const rows = Object.entries(nested).map(([field, property]) => {
    const status = required.has(field) ? "Required" : "Optional";
    const description = property.description ?? "";
    return `| \`${escapeTable(field)}\` | ${status} | ${escapeTable(schemaType(property))} | ${escapeTable(description)} |`;
  });

  return `### \`${name}\`

${schema.description ?? "Nested fields from the canonical schema."}

| Field | Status | Type | Description |
| --- | --- | --- | --- |
${rows.join("\n")}`;
}

function codeModeApiPage(): string {
  const source = readFileSync(
    join(repoRoot, "packages/core/src/code-mode/runtime-api.d.ts"),
    "utf8",
  );
  const blocks = [
    "interface CapletHandle",
    "interface DebugApi",
    "type Page",
    "type CapletsResult",
    "type ToolSummary",
    "type ToolDescriptor",
    "type ReadLogsInput",
    "type ReadLogsResult",
  ]
    .map((name) => extractDeclaration(source, name))
    .filter((block): block is string => Boolean(block));

  return `${frontmatter("Code Mode API", "Generated reference for the TypeScript surface available inside `caplets__code_mode`.")}
${generatedMarkerComment}

Code Mode runs TypeScript with generated \`caplets.<id>\` handles. Prefer discovery methods first, then call downstream tools with compact, decision-ready inputs and outputs.

## Runtime handles

${blocks.map((block) => `\`\`\`ts\n${block}\n\`\`\``).join("\n\n")}
`;
}

function changelogPage(): string {
  const changelog = readFileSync(join(repoRoot, "CHANGELOG.md"), "utf8").trim();
  const body = changelog.replace(/^# caplets\s*/u, "").trim();

  return `${frontmatter("Changelog", "Public release notes for Caplets.")}
${generatedMarkerComment}

GitHub releases: [github.com/spiritledsoftware/caplets/releases](https://github.com/spiritledsoftware/caplets/releases)

${body}
`;
}

function extractDeclaration(source: string, declaration: string): string | undefined {
  const match = new RegExp(`(^|\\n)${escapeRegExp(declaration)}(?=[<\\s=])`).exec(source);
  if (!match) return undefined;
  const start = match.index + (match[1] ? match[1].length : 0);
  const lineEnd = source.indexOf("\n", start);
  const declarationLine = source.slice(start, lineEnd === -1 ? undefined : lineEnd);
  if (!declarationLine.includes("{")) {
    const nextDeclaration = /\n(?:interface|type)\s+[A-Za-z_$]/u.exec(source.slice(lineEnd + 1));
    const end = nextDeclaration ? lineEnd + 1 + nextDeclaration.index : source.length;
    return source.slice(start, end).trim();
  }

  let index = start;
  let depth = 0;
  let seenBrace = false;
  while (index < source.length) {
    const char = source[index];
    if (char === "{") {
      depth++;
      seenBrace = true;
    } else if (char === "}") {
      depth--;
      if (seenBrace && depth === 0) {
        const semicolon = source[index + 1] === ";" ? index + 2 : index + 1;
        return source.slice(start, semicolon).trim();
      }
    }
    index++;
  }

  return undefined;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function schemaType(schema: JsonSchema): string {
  if (schema.$ref) return schema.$ref.split("/").at(-1) ?? schema.$ref;
  if (schema.enum) return schema.enum.map((value) => JSON.stringify(value)).join(" | ");
  if (schema.type) return Array.isArray(schema.type) ? schema.type.join(" | ") : schema.type;
  if (schema.oneOf) return schema.oneOf.map(schemaType).join(" | ");
  if (schema.anyOf) return schema.anyOf.map(schemaType).join(" | ");
  if (schema.allOf) return schema.allOf.map(schemaType).join(" & ");
  if (schema.additionalProperties && typeof schema.additionalProperties === "object") {
    return `record of ${schemaType(schema.additionalProperties)}`;
  }
  if (schema.properties) return "object";
  if (schema.items) return `${schemaType(schema.items)}[]`;
  return "unknown";
}

function readJsonSchema(path: string): JsonSchema {
  return JSON.parse(readFileSync(join(repoRoot, path), "utf8")) as JsonSchema;
}

function frontmatter(title: string, description: string): string {
  return `---\ntitle: ${JSON.stringify(title)}\ndescription: ${JSON.stringify(description)}\n---\n`;
}

function escapeTable(value: string): string {
  return value
    .replaceAll("|", "\\|")
    .replaceAll("{", "\\{")
    .replaceAll("}", "\\}")
    .replaceAll("\n", " ");
}

function formatMdx(value: string): string {
  const dir = mkdtempSync(join(tmpdir(), "caplets-docs-"));
  const path = join(dir, "page.mdx");
  try {
    writeFileSync(path, value);
    execFileSync("pnpm", ["exec", "oxfmt", path], { stdio: "inherit" });
    return readFileSync(path, "utf8");
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function findRepoRoot(start: string): string {
  let current = resolve(start);
  while (!existsSync(join(current, "pnpm-workspace.yaml"))) {
    const parent = dirname(current);
    if (parent === current) {
      throw new Error(`Could not find repository root from ${start}`);
    }
    current = parent;
  }
  return current;
}
