CREATE TABLE `cp_key_canary` (
	`model_version` integer NOT NULL,
	`id` text NOT NULL,
	`logical_host_id` text NOT NULL,
	`store_id` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`aggregate_version` integer NOT NULL,
	`authority_version` integer NOT NULL,
	`effective_version` integer NOT NULL,
	`security_version` integer NOT NULL,
	`purpose` text NOT NULL,
	`algorithm` text NOT NULL,
	`key_version` integer NOT NULL,
	`protection` text NOT NULL,
	`label_hash` text NOT NULL,
	`aad_version` integer NOT NULL,
	`nonce` blob,
	`ciphertext` blob,
	`auth_tag` blob,
	`verifier` blob,
	`state` text NOT NULL,
	PRIMARY KEY(`logical_host_id`, `id`),
	FOREIGN KEY (`logical_host_id`,`store_id`) REFERENCES `__caplets_storage_identity_v1`(`logical_host_id`,`store_id`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`logical_host_id`,`purpose`,`key_version`) REFERENCES `cp_key_inventory`(`logical_host_id`,`purpose`,`key_version`) ON UPDATE no action ON DELETE restrict,
	CONSTRAINT "cp_key_canary_model_version_version_check" CHECK("cp_key_canary"."model_version" >= 0),
	CONSTRAINT "cp_key_canary_id_nonempty_check" CHECK(length("cp_key_canary"."id") > 0),
	CONSTRAINT "cp_key_canary_logical_host_id_nonempty_check" CHECK(length("cp_key_canary"."logical_host_id") > 0),
	CONSTRAINT "cp_key_canary_store_id_nonempty_check" CHECK(length("cp_key_canary"."store_id") > 0),
	CONSTRAINT "cp_key_canary_created_at_nonempty_check" CHECK(length("cp_key_canary"."created_at") > 0),
	CONSTRAINT "cp_key_canary_updated_at_nonempty_check" CHECK(length("cp_key_canary"."updated_at") > 0),
	CONSTRAINT "cp_key_canary_aggregate_version_version_check" CHECK("cp_key_canary"."aggregate_version" >= 0),
	CONSTRAINT "cp_key_canary_authority_version_version_check" CHECK("cp_key_canary"."authority_version" >= 0),
	CONSTRAINT "cp_key_canary_effective_version_version_check" CHECK("cp_key_canary"."effective_version" >= 0),
	CONSTRAINT "cp_key_canary_security_version_version_check" CHECK("cp_key_canary"."security_version" >= 0),
	CONSTRAINT "cp_key_canary_purpose_nonempty_check" CHECK(length("cp_key_canary"."purpose") > 0),
	CONSTRAINT "cp_key_canary_algorithm_nonempty_check" CHECK(length("cp_key_canary"."algorithm") > 0),
	CONSTRAINT "cp_key_canary_key_version_version_check" CHECK("cp_key_canary"."key_version" >= 0),
	CONSTRAINT "cp_key_canary_protection_nonempty_check" CHECK(length("cp_key_canary"."protection") > 0),
	CONSTRAINT "cp_key_canary_label_hash_hash_check" CHECK(length("cp_key_canary"."label_hash") = 64 AND NOT "cp_key_canary"."label_hash" GLOB '*[^0-9a-f]*'),
	CONSTRAINT "cp_key_canary_aad_version_version_check" CHECK("cp_key_canary"."aad_version" >= 0),
	CONSTRAINT "cp_key_canary_nonce_bytes_check" CHECK(length("cp_key_canary"."nonce") > 0),
	CONSTRAINT "cp_key_canary_ciphertext_bytes_check" CHECK(length("cp_key_canary"."ciphertext") > 0),
	CONSTRAINT "cp_key_canary_auth_tag_bytes_check" CHECK(length("cp_key_canary"."auth_tag") > 0),
	CONSTRAINT "cp_key_canary_verifier_bytes_check" CHECK(length("cp_key_canary"."verifier") > 0),
	CONSTRAINT "cp_key_canary_state_nonempty_check" CHECK(length("cp_key_canary"."state") > 0),
	CONSTRAINT "cp_key_canary_model_version_check" CHECK("cp_key_canary"."model_version" = 1),
	CONSTRAINT "cp_key_canary_state_check" CHECK("cp_key_canary"."state" = 'active'),
	CONSTRAINT "cp_key_canary_protection_check" CHECK(("cp_key_canary"."protection" = 'aead' AND "cp_key_canary"."nonce" IS NOT NULL AND "cp_key_canary"."ciphertext" IS NOT NULL AND "cp_key_canary"."auth_tag" IS NOT NULL AND "cp_key_canary"."verifier" IS NULL) OR ("cp_key_canary"."protection" = 'hmac' AND "cp_key_canary"."nonce" IS NULL AND "cp_key_canary"."ciphertext" IS NULL AND "cp_key_canary"."auth_tag" IS NULL AND "cp_key_canary"."verifier" IS NOT NULL))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `cp_key_canary_semantic_uq` ON `cp_key_canary` (`logical_host_id`,`purpose`,`key_version`);--> statement-breakpoint
CREATE INDEX `cp_key_canary_query_1_idx` ON `cp_key_canary` (`logical_host_id`,`purpose`,`key_version`,`state`);--> statement-breakpoint
CREATE TABLE `cp_key_inventory` (
	`model_version` integer NOT NULL,
	`id` text NOT NULL,
	`logical_host_id` text NOT NULL,
	`store_id` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`aggregate_version` integer NOT NULL,
	`authority_version` integer NOT NULL,
	`effective_version` integer NOT NULL,
	`security_version` integer NOT NULL,
	`provider` text NOT NULL,
	`key_id` text NOT NULL,
	`purpose` text NOT NULL,
	`algorithm` text NOT NULL,
	`key_version` integer NOT NULL,
	`state` text NOT NULL,
	`verified_node_ids` text NOT NULL,
	`purge_watermark` integer NOT NULL,
	`activated_at` text NOT NULL,
	`decrypt_only_at` text,
	`retired_at` text,
	`destroyed_at` text,
	`destruction_id` text,
	PRIMARY KEY(`logical_host_id`, `id`),
	FOREIGN KEY (`logical_host_id`,`store_id`) REFERENCES `__caplets_storage_identity_v1`(`logical_host_id`,`store_id`) ON UPDATE no action ON DELETE restrict,
	CONSTRAINT "cp_key_inventory_model_version_version_check" CHECK("cp_key_inventory"."model_version" >= 0),
	CONSTRAINT "cp_key_inventory_id_nonempty_check" CHECK(length("cp_key_inventory"."id") > 0),
	CONSTRAINT "cp_key_inventory_logical_host_id_nonempty_check" CHECK(length("cp_key_inventory"."logical_host_id") > 0),
	CONSTRAINT "cp_key_inventory_store_id_nonempty_check" CHECK(length("cp_key_inventory"."store_id") > 0),
	CONSTRAINT "cp_key_inventory_created_at_nonempty_check" CHECK(length("cp_key_inventory"."created_at") > 0),
	CONSTRAINT "cp_key_inventory_updated_at_nonempty_check" CHECK(length("cp_key_inventory"."updated_at") > 0),
	CONSTRAINT "cp_key_inventory_aggregate_version_version_check" CHECK("cp_key_inventory"."aggregate_version" >= 0),
	CONSTRAINT "cp_key_inventory_authority_version_version_check" CHECK("cp_key_inventory"."authority_version" >= 0),
	CONSTRAINT "cp_key_inventory_effective_version_version_check" CHECK("cp_key_inventory"."effective_version" >= 0),
	CONSTRAINT "cp_key_inventory_security_version_version_check" CHECK("cp_key_inventory"."security_version" >= 0),
	CONSTRAINT "cp_key_inventory_provider_nonempty_check" CHECK(length("cp_key_inventory"."provider") > 0),
	CONSTRAINT "cp_key_inventory_key_id_nonempty_check" CHECK(length("cp_key_inventory"."key_id") > 0),
	CONSTRAINT "cp_key_inventory_purpose_nonempty_check" CHECK(length("cp_key_inventory"."purpose") > 0),
	CONSTRAINT "cp_key_inventory_algorithm_nonempty_check" CHECK(length("cp_key_inventory"."algorithm") > 0),
	CONSTRAINT "cp_key_inventory_key_version_version_check" CHECK("cp_key_inventory"."key_version" >= 0),
	CONSTRAINT "cp_key_inventory_state_nonempty_check" CHECK(length("cp_key_inventory"."state") > 0),
	CONSTRAINT "cp_key_inventory_verified_node_ids_json_check" CHECK(json_valid("cp_key_inventory"."verified_node_ids")),
	CONSTRAINT "cp_key_inventory_purge_watermark_version_check" CHECK("cp_key_inventory"."purge_watermark" >= 0),
	CONSTRAINT "cp_key_inventory_activated_at_nonempty_check" CHECK(length("cp_key_inventory"."activated_at") > 0),
	CONSTRAINT "cp_key_inventory_decrypt_only_at_nonempty_check" CHECK(length("cp_key_inventory"."decrypt_only_at") > 0),
	CONSTRAINT "cp_key_inventory_retired_at_nonempty_check" CHECK(length("cp_key_inventory"."retired_at") > 0),
	CONSTRAINT "cp_key_inventory_destroyed_at_nonempty_check" CHECK(length("cp_key_inventory"."destroyed_at") > 0),
	CONSTRAINT "cp_key_inventory_destruction_id_nonempty_check" CHECK(length("cp_key_inventory"."destruction_id") > 0),
	CONSTRAINT "cp_key_inventory_model_version_check" CHECK("cp_key_inventory"."model_version" = 1),
	CONSTRAINT "cp_key_inventory_provider_check" CHECK("cp_key_inventory"."provider" = 'file-v1'),
	CONSTRAINT "cp_key_inventory_state_check" CHECK("cp_key_inventory"."state" IN ('active', 'decrypt-only', 'retired', 'destruction-intended', 'destroyed'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `cp_key_inventory_semantic_uq` ON `cp_key_inventory` (`logical_host_id`,`purpose`,`key_version`);--> statement-breakpoint
CREATE INDEX `cp_key_inventory_query_1_idx` ON `cp_key_inventory` (`logical_host_id`,`purpose`,`state`);--> statement-breakpoint
CREATE INDEX `cp_key_inventory_query_2_idx` ON `cp_key_inventory` (`logical_host_id`,`purge_watermark`);--> statement-breakpoint
CREATE UNIQUE INDEX `cp_key_inventory_relation_target_uq` ON `cp_key_inventory` (`logical_host_id`,`purpose`,`key_version`);--> statement-breakpoint
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_cp_operator_activity` (
	`model_version` integer NOT NULL,
	`id` text NOT NULL,
	`logical_host_id` text NOT NULL,
	`store_id` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`aggregate_version` integer NOT NULL,
	`authority_version` integer NOT NULL,
	`effective_version` integer NOT NULL,
	`security_version` integer NOT NULL,
	`activity_id` text NOT NULL,
	`actor_id` text NOT NULL,
	`action` text NOT NULL,
	`outcome` text NOT NULL,
	`target` text NOT NULL,
	`redacted_detail` text,
	`occurred_at` text NOT NULL,
	`expires_at` text NOT NULL,
	PRIMARY KEY(`logical_host_id`, `id`),
	FOREIGN KEY (`logical_host_id`,`store_id`) REFERENCES `__caplets_storage_identity_v1`(`logical_host_id`,`store_id`) ON UPDATE no action ON DELETE restrict,
	CONSTRAINT "cp_operator_activity_model_version_version_check" CHECK("__new_cp_operator_activity"."model_version" >= 0),
	CONSTRAINT "cp_operator_activity_id_nonempty_check" CHECK(length("__new_cp_operator_activity"."id") > 0),
	CONSTRAINT "cp_operator_activity_logical_host_id_nonempty_check" CHECK(length("__new_cp_operator_activity"."logical_host_id") > 0),
	CONSTRAINT "cp_operator_activity_store_id_nonempty_check" CHECK(length("__new_cp_operator_activity"."store_id") > 0),
	CONSTRAINT "cp_operator_activity_created_at_nonempty_check" CHECK(length("__new_cp_operator_activity"."created_at") > 0),
	CONSTRAINT "cp_operator_activity_updated_at_nonempty_check" CHECK(length("__new_cp_operator_activity"."updated_at") > 0),
	CONSTRAINT "cp_operator_activity_aggregate_version_version_check" CHECK("__new_cp_operator_activity"."aggregate_version" >= 0),
	CONSTRAINT "cp_operator_activity_authority_version_version_check" CHECK("__new_cp_operator_activity"."authority_version" >= 0),
	CONSTRAINT "cp_operator_activity_effective_version_version_check" CHECK("__new_cp_operator_activity"."effective_version" >= 0),
	CONSTRAINT "cp_operator_activity_security_version_version_check" CHECK("__new_cp_operator_activity"."security_version" >= 0),
	CONSTRAINT "cp_operator_activity_activity_id_nonempty_check" CHECK(length("__new_cp_operator_activity"."activity_id") > 0),
	CONSTRAINT "cp_operator_activity_actor_id_nonempty_check" CHECK(length("__new_cp_operator_activity"."actor_id") > 0),
	CONSTRAINT "cp_operator_activity_action_nonempty_check" CHECK(length("__new_cp_operator_activity"."action") > 0),
	CONSTRAINT "cp_operator_activity_outcome_nonempty_check" CHECK(length("__new_cp_operator_activity"."outcome") > 0),
	CONSTRAINT "cp_operator_activity_target_json_check" CHECK(json_valid("__new_cp_operator_activity"."target")),
	CONSTRAINT "cp_operator_activity_redacted_detail_json_check" CHECK(json_valid("__new_cp_operator_activity"."redacted_detail")),
	CONSTRAINT "cp_operator_activity_occurred_at_nonempty_check" CHECK(length("__new_cp_operator_activity"."occurred_at") > 0),
	CONSTRAINT "cp_operator_activity_expires_at_nonempty_check" CHECK(length("__new_cp_operator_activity"."expires_at") > 0),
	CONSTRAINT "cp_operator_activity_model_version_check" CHECK("__new_cp_operator_activity"."model_version" = 1)
);
--> statement-breakpoint
INSERT INTO `__new_cp_operator_activity`("model_version", "id", "logical_host_id", "store_id", "created_at", "updated_at", "aggregate_version", "authority_version", "effective_version", "security_version", "activity_id", "actor_id", "action", "outcome", "target", "redacted_detail", "occurred_at", "expires_at") SELECT "model_version", "id", "logical_host_id", "store_id", "created_at", "updated_at", "aggregate_version", "authority_version", "effective_version", "security_version", "activity_id", "actor_id", "action", "outcome", "target", "redacted_detail", "occurred_at", strftime('%Y-%m-%dT%H:%M:%fZ', "occurred_at", '+90 days') FROM `cp_operator_activity`;--> statement-breakpoint
DROP TABLE `cp_operator_activity`;--> statement-breakpoint
ALTER TABLE `__new_cp_operator_activity` RENAME TO `cp_operator_activity`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE UNIQUE INDEX `cp_operator_activity_semantic_uq` ON `cp_operator_activity` (`logical_host_id`,`activity_id`);--> statement-breakpoint
CREATE INDEX `cp_operator_activity_query_1_idx` ON `cp_operator_activity` (`logical_host_id`,`occurred_at`);--> statement-breakpoint
CREATE INDEX `cp_operator_activity_query_2_idx` ON `cp_operator_activity` (`logical_host_id`,`expires_at`);--> statement-breakpoint
CREATE INDEX `cp_operator_activity_query_3_idx` ON `cp_operator_activity` (`logical_host_id`,`action`);--> statement-breakpoint
DROP INDEX `cp_vault_grant_semantic_uq`;--> statement-breakpoint
CREATE UNIQUE INDEX `cp_vault_grant_semantic_uq` ON `cp_vault_grant` (`logical_host_id`,`reference_name`,`caplet_id`,`origin`);--> statement-breakpoint
CREATE TABLE `__new_cp_backup` (
	`model_version` integer NOT NULL,
	`id` text NOT NULL,
	`logical_host_id` text NOT NULL,
	`store_id` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`aggregate_version` integer NOT NULL,
	`authority_version` integer NOT NULL,
	`effective_version` integer NOT NULL,
	`security_version` integer NOT NULL,
	`backup_id` text NOT NULL,
	`provider_identity` text NOT NULL,
	`source_identity` text NOT NULL,
	`source_profile` text NOT NULL,
	`manifest_hash` text NOT NULL,
	`key_version` integer NOT NULL,
	`key_purpose` text NOT NULL,
	`key_algorithm` text NOT NULL,
	`unwrap_identity` text NOT NULL,
	`retention_until` text NOT NULL,
	`state` text NOT NULL,
	`destroyed_at` text,
	`destruction_id` text,
	PRIMARY KEY(`logical_host_id`, `id`),
	FOREIGN KEY (`logical_host_id`,`store_id`) REFERENCES `__caplets_storage_identity_v1`(`logical_host_id`,`store_id`) ON UPDATE no action ON DELETE restrict,
	CONSTRAINT "cp_backup_model_version_version_check" CHECK("__new_cp_backup"."model_version" >= 0),
	CONSTRAINT "cp_backup_id_nonempty_check" CHECK(length("__new_cp_backup"."id") > 0),
	CONSTRAINT "cp_backup_logical_host_id_nonempty_check" CHECK(length("__new_cp_backup"."logical_host_id") > 0),
	CONSTRAINT "cp_backup_store_id_nonempty_check" CHECK(length("__new_cp_backup"."store_id") > 0),
	CONSTRAINT "cp_backup_created_at_nonempty_check" CHECK(length("__new_cp_backup"."created_at") > 0),
	CONSTRAINT "cp_backup_updated_at_nonempty_check" CHECK(length("__new_cp_backup"."updated_at") > 0),
	CONSTRAINT "cp_backup_aggregate_version_version_check" CHECK("__new_cp_backup"."aggregate_version" >= 0),
	CONSTRAINT "cp_backup_authority_version_version_check" CHECK("__new_cp_backup"."authority_version" >= 0),
	CONSTRAINT "cp_backup_effective_version_version_check" CHECK("__new_cp_backup"."effective_version" >= 0),
	CONSTRAINT "cp_backup_security_version_version_check" CHECK("__new_cp_backup"."security_version" >= 0),
	CONSTRAINT "cp_backup_backup_id_nonempty_check" CHECK(length("__new_cp_backup"."backup_id") > 0),
	CONSTRAINT "cp_backup_provider_identity_nonempty_check" CHECK(length("__new_cp_backup"."provider_identity") > 0),
	CONSTRAINT "cp_backup_source_identity_nonempty_check" CHECK(length("__new_cp_backup"."source_identity") > 0),
	CONSTRAINT "cp_backup_source_profile_nonempty_check" CHECK(length("__new_cp_backup"."source_profile") > 0),
	CONSTRAINT "cp_backup_manifest_hash_hash_check" CHECK(length("__new_cp_backup"."manifest_hash") = 64 AND NOT "__new_cp_backup"."manifest_hash" GLOB '*[^0-9a-f]*'),
	CONSTRAINT "cp_backup_key_version_version_check" CHECK("__new_cp_backup"."key_version" >= 0),
	CONSTRAINT "cp_backup_key_purpose_nonempty_check" CHECK(length("__new_cp_backup"."key_purpose") > 0),
	CONSTRAINT "cp_backup_key_algorithm_nonempty_check" CHECK(length("__new_cp_backup"."key_algorithm") > 0),
	CONSTRAINT "cp_backup_unwrap_identity_nonempty_check" CHECK(length("__new_cp_backup"."unwrap_identity") > 0),
	CONSTRAINT "cp_backup_retention_until_nonempty_check" CHECK(length("__new_cp_backup"."retention_until") > 0),
	CONSTRAINT "cp_backup_state_nonempty_check" CHECK(length("__new_cp_backup"."state") > 0),
	CONSTRAINT "cp_backup_destroyed_at_nonempty_check" CHECK(length("__new_cp_backup"."destroyed_at") > 0),
	CONSTRAINT "cp_backup_destruction_id_nonempty_check" CHECK(length("__new_cp_backup"."destruction_id") > 0),
	CONSTRAINT "cp_backup_model_version_check" CHECK("__new_cp_backup"."model_version" = 1)
);
--> statement-breakpoint
INSERT INTO `__new_cp_backup`("model_version", "id", "logical_host_id", "store_id", "created_at", "updated_at", "aggregate_version", "authority_version", "effective_version", "security_version", "backup_id", "provider_identity", "source_identity", "source_profile", "manifest_hash", "key_version", "key_purpose", "key_algorithm", "unwrap_identity", "retention_until", "state", "destroyed_at", "destruction_id") SELECT "model_version", "id", "logical_host_id", "store_id", "created_at", "updated_at", "aggregate_version", "authority_version", "effective_version", "security_version", "backup_id", "provider_identity", "source_identity", "source_profile", "manifest_hash", "key_version", 'backup-recovery', 'RSA-OAEP-256', "unwrap_identity", "retention_until", "state", NULL, NULL FROM `cp_backup`;--> statement-breakpoint
DROP TABLE `cp_backup`;--> statement-breakpoint
ALTER TABLE `__new_cp_backup` RENAME TO `cp_backup`;--> statement-breakpoint
CREATE UNIQUE INDEX `cp_backup_semantic_uq` ON `cp_backup` (`logical_host_id`,`backup_id`);--> statement-breakpoint
CREATE INDEX `cp_backup_query_1_idx` ON `cp_backup` (`logical_host_id`,`retention_until`,`state`);--> statement-breakpoint
CREATE UNIQUE INDEX `cp_backup_relation_target_uq` ON `cp_backup` (`logical_host_id`,`backup_id`);--> statement-breakpoint
CREATE TABLE `__new_cp_client` (
	`model_version` integer NOT NULL,
	`id` text NOT NULL,
	`logical_host_id` text NOT NULL,
	`store_id` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`aggregate_version` integer NOT NULL,
	`authority_version` integer NOT NULL,
	`effective_version` integer NOT NULL,
	`security_version` integer NOT NULL,
	`client_id` text NOT NULL,
	`role` text NOT NULL,
	`status` text NOT NULL,
	`host_url` text NOT NULL,
	`client_label` text NOT NULL,
	`owner_id` text,
	`last_authenticated_at` text,
	`revoked_at` text,
	PRIMARY KEY(`logical_host_id`, `id`),
	FOREIGN KEY (`logical_host_id`,`store_id`) REFERENCES `__caplets_storage_identity_v1`(`logical_host_id`,`store_id`) ON UPDATE no action ON DELETE restrict,
	CONSTRAINT "cp_client_model_version_version_check" CHECK("__new_cp_client"."model_version" >= 0),
	CONSTRAINT "cp_client_id_nonempty_check" CHECK(length("__new_cp_client"."id") > 0),
	CONSTRAINT "cp_client_logical_host_id_nonempty_check" CHECK(length("__new_cp_client"."logical_host_id") > 0),
	CONSTRAINT "cp_client_store_id_nonempty_check" CHECK(length("__new_cp_client"."store_id") > 0),
	CONSTRAINT "cp_client_created_at_nonempty_check" CHECK(length("__new_cp_client"."created_at") > 0),
	CONSTRAINT "cp_client_updated_at_nonempty_check" CHECK(length("__new_cp_client"."updated_at") > 0),
	CONSTRAINT "cp_client_aggregate_version_version_check" CHECK("__new_cp_client"."aggregate_version" >= 0),
	CONSTRAINT "cp_client_authority_version_version_check" CHECK("__new_cp_client"."authority_version" >= 0),
	CONSTRAINT "cp_client_effective_version_version_check" CHECK("__new_cp_client"."effective_version" >= 0),
	CONSTRAINT "cp_client_security_version_version_check" CHECK("__new_cp_client"."security_version" >= 0),
	CONSTRAINT "cp_client_client_id_nonempty_check" CHECK(length("__new_cp_client"."client_id") > 0),
	CONSTRAINT "cp_client_role_nonempty_check" CHECK(length("__new_cp_client"."role") > 0),
	CONSTRAINT "cp_client_status_nonempty_check" CHECK(length("__new_cp_client"."status") > 0),
	CONSTRAINT "cp_client_host_url_nonempty_check" CHECK(length("__new_cp_client"."host_url") > 0),
	CONSTRAINT "cp_client_client_label_nonempty_check" CHECK(length("__new_cp_client"."client_label") > 0),
	CONSTRAINT "cp_client_owner_id_nonempty_check" CHECK(length("__new_cp_client"."owner_id") > 0),
	CONSTRAINT "cp_client_last_authenticated_at_nonempty_check" CHECK(length("__new_cp_client"."last_authenticated_at") > 0),
	CONSTRAINT "cp_client_revoked_at_nonempty_check" CHECK(length("__new_cp_client"."revoked_at") > 0),
	CONSTRAINT "cp_client_model_version_check" CHECK("__new_cp_client"."model_version" = 1)
);
--> statement-breakpoint
INSERT INTO `__new_cp_client`("model_version", "id", "logical_host_id", "store_id", "created_at", "updated_at", "aggregate_version", "authority_version", "effective_version", "security_version", "client_id", "role", "status", "host_url", "client_label", "owner_id", "last_authenticated_at", "revoked_at") SELECT "model_version", "id", "logical_host_id", "store_id", "created_at", "updated_at", "aggregate_version", "authority_version", "effective_version", "security_version", "client_id", "role", "status", 'legacy-unbound', "client_id", "owner_id", "last_authenticated_at", "revoked_at" FROM `cp_client`;--> statement-breakpoint
DROP TABLE `cp_client`;--> statement-breakpoint
ALTER TABLE `__new_cp_client` RENAME TO `cp_client`;--> statement-breakpoint
CREATE UNIQUE INDEX `cp_client_semantic_uq` ON `cp_client` (`logical_host_id`,`client_id`);--> statement-breakpoint
CREATE INDEX `cp_client_query_1_idx` ON `cp_client` (`logical_host_id`,`status`);--> statement-breakpoint
CREATE UNIQUE INDEX `cp_client_relation_target_uq` ON `cp_client` (`logical_host_id`,`client_id`);--> statement-breakpoint
CREATE TABLE `__new_cp_credential` (
	`model_version` integer NOT NULL,
	`id` text NOT NULL,
	`logical_host_id` text NOT NULL,
	`store_id` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`aggregate_version` integer NOT NULL,
	`authority_version` integer NOT NULL,
	`effective_version` integer NOT NULL,
	`security_version` integer NOT NULL,
	`credential_id` text NOT NULL,
	`client_id` text,
	`purpose` text NOT NULL,
	`protection` text NOT NULL,
	`verifier_or_ciphertext` blob NOT NULL,
	`algorithm` text NOT NULL,
	`verifier_version` integer NOT NULL,
	`access_ciphertext` blob,
	`refresh_ciphertext` blob,
	`workspace` text,
	`record_version` integer,
	`owner_id` text,
	`key_version` integer NOT NULL,
	`expires_at` text,
	`refresh_family_id` text,
	`consumed_at` text,
	PRIMARY KEY(`logical_host_id`, `id`),
	FOREIGN KEY (`logical_host_id`,`store_id`) REFERENCES `__caplets_storage_identity_v1`(`logical_host_id`,`store_id`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`logical_host_id`,`client_id`) REFERENCES `cp_client`(`logical_host_id`,`client_id`) ON UPDATE no action ON DELETE restrict,
	CONSTRAINT "cp_credential_model_version_version_check" CHECK("__new_cp_credential"."model_version" >= 0),
	CONSTRAINT "cp_credential_id_nonempty_check" CHECK(length("__new_cp_credential"."id") > 0),
	CONSTRAINT "cp_credential_logical_host_id_nonempty_check" CHECK(length("__new_cp_credential"."logical_host_id") > 0),
	CONSTRAINT "cp_credential_store_id_nonempty_check" CHECK(length("__new_cp_credential"."store_id") > 0),
	CONSTRAINT "cp_credential_created_at_nonempty_check" CHECK(length("__new_cp_credential"."created_at") > 0),
	CONSTRAINT "cp_credential_updated_at_nonempty_check" CHECK(length("__new_cp_credential"."updated_at") > 0),
	CONSTRAINT "cp_credential_aggregate_version_version_check" CHECK("__new_cp_credential"."aggregate_version" >= 0),
	CONSTRAINT "cp_credential_authority_version_version_check" CHECK("__new_cp_credential"."authority_version" >= 0),
	CONSTRAINT "cp_credential_effective_version_version_check" CHECK("__new_cp_credential"."effective_version" >= 0),
	CONSTRAINT "cp_credential_security_version_version_check" CHECK("__new_cp_credential"."security_version" >= 0),
	CONSTRAINT "cp_credential_credential_id_nonempty_check" CHECK(length("__new_cp_credential"."credential_id") > 0),
	CONSTRAINT "cp_credential_client_id_nonempty_check" CHECK(length("__new_cp_credential"."client_id") > 0),
	CONSTRAINT "cp_credential_purpose_nonempty_check" CHECK(length("__new_cp_credential"."purpose") > 0),
	CONSTRAINT "cp_credential_protection_nonempty_check" CHECK(length("__new_cp_credential"."protection") > 0),
	CONSTRAINT "cp_credential_verifier_or_ciphertext_bytes_check" CHECK(length("__new_cp_credential"."verifier_or_ciphertext") > 0),
	CONSTRAINT "cp_credential_algorithm_nonempty_check" CHECK(length("__new_cp_credential"."algorithm") > 0),
	CONSTRAINT "cp_credential_verifier_version_version_check" CHECK("__new_cp_credential"."verifier_version" >= 0),
	CONSTRAINT "cp_credential_access_ciphertext_bytes_check" CHECK(length("__new_cp_credential"."access_ciphertext") > 0),
	CONSTRAINT "cp_credential_refresh_ciphertext_bytes_check" CHECK(length("__new_cp_credential"."refresh_ciphertext") > 0),
	CONSTRAINT "cp_credential_workspace_nonempty_check" CHECK(length("__new_cp_credential"."workspace") > 0),
	CONSTRAINT "cp_credential_record_version_version_check" CHECK("__new_cp_credential"."record_version" >= 0),
	CONSTRAINT "cp_credential_owner_id_nonempty_check" CHECK(length("__new_cp_credential"."owner_id") > 0),
	CONSTRAINT "cp_credential_key_version_version_check" CHECK("__new_cp_credential"."key_version" >= 0),
	CONSTRAINT "cp_credential_expires_at_nonempty_check" CHECK(length("__new_cp_credential"."expires_at") > 0),
	CONSTRAINT "cp_credential_refresh_family_id_nonempty_check" CHECK(length("__new_cp_credential"."refresh_family_id") > 0),
	CONSTRAINT "cp_credential_consumed_at_nonempty_check" CHECK(length("__new_cp_credential"."consumed_at") > 0),
	CONSTRAINT "cp_credential_model_version_check" CHECK("__new_cp_credential"."model_version" = 1)
);
--> statement-breakpoint
INSERT INTO `__new_cp_credential`("model_version", "id", "logical_host_id", "store_id", "created_at", "updated_at", "aggregate_version", "authority_version", "effective_version", "security_version", "credential_id", "client_id", "purpose", "protection", "verifier_or_ciphertext", "algorithm", "verifier_version", "access_ciphertext", "refresh_ciphertext", "workspace", "record_version", "owner_id", "key_version", "expires_at", "refresh_family_id", "consumed_at") SELECT "model_version", "id", "logical_host_id", "store_id", "created_at", "updated_at", "aggregate_version", "authority_version", "effective_version", "security_version", "credential_id", "client_id", "purpose", "protection", "verifier_or_ciphertext", 'legacy-unclassified', 0, "access_ciphertext", "refresh_ciphertext", "workspace", "record_version", "owner_id", "key_version", "expires_at", "refresh_family_id", "consumed_at" FROM `cp_credential`;--> statement-breakpoint
DROP TABLE `cp_credential`;--> statement-breakpoint
ALTER TABLE `__new_cp_credential` RENAME TO `cp_credential`;--> statement-breakpoint
CREATE UNIQUE INDEX `cp_credential_semantic_uq` ON `cp_credential` (`logical_host_id`,`credential_id`);--> statement-breakpoint
CREATE INDEX `cp_credential_query_1_idx` ON `cp_credential` (`logical_host_id`,`client_id`,`expires_at`);--> statement-breakpoint
CREATE TABLE `__new_cp_dashboard_session` (
	`model_version` integer NOT NULL,
	`id` text NOT NULL,
	`logical_host_id` text NOT NULL,
	`store_id` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`aggregate_version` integer NOT NULL,
	`authority_version` integer NOT NULL,
	`effective_version` integer NOT NULL,
	`security_version` integer NOT NULL,
	`session_id` text NOT NULL,
	`client_id` text NOT NULL,
	`verifier` blob NOT NULL,
	`algorithm` text NOT NULL,
	`verifier_version` integer NOT NULL,
	`key_version` integer NOT NULL,
	`csrf_verifier` blob NOT NULL,
	`csrf_algorithm` text NOT NULL,
	`csrf_key_version` integer NOT NULL,
	`absolute_expires_at` text NOT NULL,
	`idle_expires_at` text NOT NULL,
	`expires_at` text NOT NULL,
	`last_seen_at` text,
	`revoked_at` text,
	PRIMARY KEY(`logical_host_id`, `id`),
	FOREIGN KEY (`logical_host_id`,`store_id`) REFERENCES `__caplets_storage_identity_v1`(`logical_host_id`,`store_id`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`logical_host_id`,`client_id`) REFERENCES `cp_client`(`logical_host_id`,`client_id`) ON UPDATE no action ON DELETE restrict,
	CONSTRAINT "cp_dashboard_session_model_version_version_check" CHECK("__new_cp_dashboard_session"."model_version" >= 0),
	CONSTRAINT "cp_dashboard_session_id_nonempty_check" CHECK(length("__new_cp_dashboard_session"."id") > 0),
	CONSTRAINT "cp_dashboard_session_logical_host_id_nonempty_check" CHECK(length("__new_cp_dashboard_session"."logical_host_id") > 0),
	CONSTRAINT "cp_dashboard_session_store_id_nonempty_check" CHECK(length("__new_cp_dashboard_session"."store_id") > 0),
	CONSTRAINT "cp_dashboard_session_created_at_nonempty_check" CHECK(length("__new_cp_dashboard_session"."created_at") > 0),
	CONSTRAINT "cp_dashboard_session_updated_at_nonempty_check" CHECK(length("__new_cp_dashboard_session"."updated_at") > 0),
	CONSTRAINT "cp_dashboard_session_aggregate_version_version_check" CHECK("__new_cp_dashboard_session"."aggregate_version" >= 0),
	CONSTRAINT "cp_dashboard_session_authority_version_version_check" CHECK("__new_cp_dashboard_session"."authority_version" >= 0),
	CONSTRAINT "cp_dashboard_session_effective_version_version_check" CHECK("__new_cp_dashboard_session"."effective_version" >= 0),
	CONSTRAINT "cp_dashboard_session_security_version_version_check" CHECK("__new_cp_dashboard_session"."security_version" >= 0),
	CONSTRAINT "cp_dashboard_session_session_id_nonempty_check" CHECK(length("__new_cp_dashboard_session"."session_id") > 0),
	CONSTRAINT "cp_dashboard_session_client_id_nonempty_check" CHECK(length("__new_cp_dashboard_session"."client_id") > 0),
	CONSTRAINT "cp_dashboard_session_verifier_bytes_check" CHECK(length("__new_cp_dashboard_session"."verifier") > 0),
	CONSTRAINT "cp_dashboard_session_algorithm_nonempty_check" CHECK(length("__new_cp_dashboard_session"."algorithm") > 0),
	CONSTRAINT "cp_dashboard_session_verifier_version_version_check" CHECK("__new_cp_dashboard_session"."verifier_version" >= 0),
	CONSTRAINT "cp_dashboard_session_key_version_version_check" CHECK("__new_cp_dashboard_session"."key_version" >= 0),
	CONSTRAINT "cp_dashboard_session_csrf_verifier_bytes_check" CHECK(length("__new_cp_dashboard_session"."csrf_verifier") > 0),
	CONSTRAINT "cp_dashboard_session_csrf_algorithm_nonempty_check" CHECK(length("__new_cp_dashboard_session"."csrf_algorithm") > 0),
	CONSTRAINT "cp_dashboard_session_csrf_key_version_version_check" CHECK("__new_cp_dashboard_session"."csrf_key_version" >= 0),
	CONSTRAINT "cp_dashboard_session_absolute_expires_at_nonempty_check" CHECK(length("__new_cp_dashboard_session"."absolute_expires_at") > 0),
	CONSTRAINT "cp_dashboard_session_idle_expires_at_nonempty_check" CHECK(length("__new_cp_dashboard_session"."idle_expires_at") > 0),
	CONSTRAINT "cp_dashboard_session_expires_at_nonempty_check" CHECK(length("__new_cp_dashboard_session"."expires_at") > 0),
	CONSTRAINT "cp_dashboard_session_last_seen_at_nonempty_check" CHECK(length("__new_cp_dashboard_session"."last_seen_at") > 0),
	CONSTRAINT "cp_dashboard_session_revoked_at_nonempty_check" CHECK(length("__new_cp_dashboard_session"."revoked_at") > 0),
	CONSTRAINT "cp_dashboard_session_model_version_check" CHECK("__new_cp_dashboard_session"."model_version" = 1)
);
--> statement-breakpoint
INSERT INTO `__new_cp_dashboard_session`("model_version", "id", "logical_host_id", "store_id", "created_at", "updated_at", "aggregate_version", "authority_version", "effective_version", "security_version", "session_id", "client_id", "verifier", "algorithm", "verifier_version", "key_version", "csrf_verifier", "csrf_algorithm", "csrf_key_version", "absolute_expires_at", "idle_expires_at", "expires_at", "last_seen_at", "revoked_at") SELECT "model_version", "id", "logical_host_id", "store_id", "created_at", "updated_at", "aggregate_version", "authority_version", "effective_version", "security_version", "session_id", "client_id", "verifier", 'legacy-invalidated', 0, 0, "verifier", 'legacy-invalidated', 0, "expires_at", COALESCE("last_seen_at", "created_at"), "expires_at", "last_seen_at", COALESCE("revoked_at", "updated_at") FROM `cp_dashboard_session`;--> statement-breakpoint
DROP TABLE `cp_dashboard_session`;--> statement-breakpoint
ALTER TABLE `__new_cp_dashboard_session` RENAME TO `cp_dashboard_session`;--> statement-breakpoint
CREATE UNIQUE INDEX `cp_dashboard_session_semantic_uq` ON `cp_dashboard_session` (`logical_host_id`,`session_id`);--> statement-breakpoint
CREATE INDEX `cp_dashboard_session_query_1_idx` ON `cp_dashboard_session` (`logical_host_id`,`expires_at`,`revoked_at`);--> statement-breakpoint
CREATE TABLE `__new_cp_oauth_token` (
	`model_version` integer NOT NULL,
	`id` text NOT NULL,
	`logical_host_id` text NOT NULL,
	`store_id` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`aggregate_version` integer NOT NULL,
	`authority_version` integer NOT NULL,
	`effective_version` integer NOT NULL,
	`security_version` integer NOT NULL,
	`server_name` text NOT NULL,
	`owner_id` text,
	`access_ciphertext` blob NOT NULL,
	`nonce` blob NOT NULL,
	`auth_tag` blob NOT NULL,
	`refresh_ciphertext` blob,
	`auth_type` text,
	`id_token_ciphertext` blob,
	`issuer` text,
	`subject` text,
	`client_id` text,
	`client_secret_ciphertext` blob,
	`protected_resource_origin` text,
	`metadata` text,
	`token_type` text,
	`scope` text,
	`expires_at` text,
	`key_version` integer NOT NULL,
	`record_version` integer NOT NULL,
	`algorithm` text NOT NULL,
	`aad_version` integer NOT NULL,
	PRIMARY KEY(`logical_host_id`, `id`),
	FOREIGN KEY (`logical_host_id`,`store_id`) REFERENCES `__caplets_storage_identity_v1`(`logical_host_id`,`store_id`) ON UPDATE no action ON DELETE restrict,
	CONSTRAINT "cp_oauth_token_model_version_version_check" CHECK("__new_cp_oauth_token"."model_version" >= 0),
	CONSTRAINT "cp_oauth_token_id_nonempty_check" CHECK(length("__new_cp_oauth_token"."id") > 0),
	CONSTRAINT "cp_oauth_token_logical_host_id_nonempty_check" CHECK(length("__new_cp_oauth_token"."logical_host_id") > 0),
	CONSTRAINT "cp_oauth_token_store_id_nonempty_check" CHECK(length("__new_cp_oauth_token"."store_id") > 0),
	CONSTRAINT "cp_oauth_token_created_at_nonempty_check" CHECK(length("__new_cp_oauth_token"."created_at") > 0),
	CONSTRAINT "cp_oauth_token_updated_at_nonempty_check" CHECK(length("__new_cp_oauth_token"."updated_at") > 0),
	CONSTRAINT "cp_oauth_token_aggregate_version_version_check" CHECK("__new_cp_oauth_token"."aggregate_version" >= 0),
	CONSTRAINT "cp_oauth_token_authority_version_version_check" CHECK("__new_cp_oauth_token"."authority_version" >= 0),
	CONSTRAINT "cp_oauth_token_effective_version_version_check" CHECK("__new_cp_oauth_token"."effective_version" >= 0),
	CONSTRAINT "cp_oauth_token_security_version_version_check" CHECK("__new_cp_oauth_token"."security_version" >= 0),
	CONSTRAINT "cp_oauth_token_server_name_nonempty_check" CHECK(length("__new_cp_oauth_token"."server_name") > 0),
	CONSTRAINT "cp_oauth_token_owner_id_nonempty_check" CHECK(length("__new_cp_oauth_token"."owner_id") > 0),
	CONSTRAINT "cp_oauth_token_access_ciphertext_bytes_check" CHECK(length("__new_cp_oauth_token"."access_ciphertext") > 0),
	CONSTRAINT "cp_oauth_token_nonce_bytes_check" CHECK(length("__new_cp_oauth_token"."nonce") > 0),
	CONSTRAINT "cp_oauth_token_auth_tag_bytes_check" CHECK(length("__new_cp_oauth_token"."auth_tag") > 0),
	CONSTRAINT "cp_oauth_token_refresh_ciphertext_bytes_check" CHECK(length("__new_cp_oauth_token"."refresh_ciphertext") > 0),
	CONSTRAINT "cp_oauth_token_auth_type_nonempty_check" CHECK(length("__new_cp_oauth_token"."auth_type") > 0),
	CONSTRAINT "cp_oauth_token_id_token_ciphertext_bytes_check" CHECK(length("__new_cp_oauth_token"."id_token_ciphertext") > 0),
	CONSTRAINT "cp_oauth_token_issuer_nonempty_check" CHECK(length("__new_cp_oauth_token"."issuer") > 0),
	CONSTRAINT "cp_oauth_token_subject_nonempty_check" CHECK(length("__new_cp_oauth_token"."subject") > 0),
	CONSTRAINT "cp_oauth_token_client_id_nonempty_check" CHECK(length("__new_cp_oauth_token"."client_id") > 0),
	CONSTRAINT "cp_oauth_token_client_secret_ciphertext_bytes_check" CHECK(length("__new_cp_oauth_token"."client_secret_ciphertext") > 0),
	CONSTRAINT "cp_oauth_token_protected_resource_origin_nonempty_check" CHECK(length("__new_cp_oauth_token"."protected_resource_origin") > 0),
	CONSTRAINT "cp_oauth_token_metadata_json_check" CHECK(json_valid("__new_cp_oauth_token"."metadata")),
	CONSTRAINT "cp_oauth_token_token_type_nonempty_check" CHECK(length("__new_cp_oauth_token"."token_type") > 0),
	CONSTRAINT "cp_oauth_token_scope_json_check" CHECK(json_valid("__new_cp_oauth_token"."scope")),
	CONSTRAINT "cp_oauth_token_expires_at_nonempty_check" CHECK(length("__new_cp_oauth_token"."expires_at") > 0),
	CONSTRAINT "cp_oauth_token_key_version_version_check" CHECK("__new_cp_oauth_token"."key_version" >= 0),
	CONSTRAINT "cp_oauth_token_record_version_version_check" CHECK("__new_cp_oauth_token"."record_version" >= 0),
	CONSTRAINT "cp_oauth_token_algorithm_nonempty_check" CHECK(length("__new_cp_oauth_token"."algorithm") > 0),
	CONSTRAINT "cp_oauth_token_aad_version_version_check" CHECK("__new_cp_oauth_token"."aad_version" >= 0),
	CONSTRAINT "cp_oauth_token_model_version_check" CHECK("__new_cp_oauth_token"."model_version" = 1)
);
--> statement-breakpoint
INSERT INTO `__new_cp_oauth_token`("model_version", "id", "logical_host_id", "store_id", "created_at", "updated_at", "aggregate_version", "authority_version", "effective_version", "security_version", "server_name", "owner_id", "access_ciphertext", "nonce", "auth_tag", "refresh_ciphertext", "auth_type", "id_token_ciphertext", "issuer", "subject", "client_id", "client_secret_ciphertext", "protected_resource_origin", "metadata", "token_type", "scope", "expires_at", "key_version", "record_version", "algorithm", "aad_version") SELECT "model_version", "id", "logical_host_id", "store_id", "created_at", "updated_at", "aggregate_version", "authority_version", "effective_version", "security_version", "server_name", "owner_id", "access_ciphertext", x'00', x'00', "refresh_ciphertext", "auth_type", "id_token_ciphertext", "issuer", "subject", "client_id", "client_secret_ciphertext", "protected_resource_origin", "metadata", "token_type", "scope", "expires_at", "key_version", "record_version", 'legacy-invalidated', 0 FROM `cp_oauth_token`;--> statement-breakpoint
DROP TABLE `cp_oauth_token`;--> statement-breakpoint
ALTER TABLE `__new_cp_oauth_token` RENAME TO `cp_oauth_token`;--> statement-breakpoint
CREATE INDEX `cp_oauth_token_query_1_idx` ON `cp_oauth_token` (`logical_host_id`,`server_name`,`owner_id`);--> statement-breakpoint
CREATE INDEX `cp_oauth_token_query_2_idx` ON `cp_oauth_token` (`logical_host_id`,`expires_at`);--> statement-breakpoint
CREATE TABLE `__new_cp_pending_approval` (
	`model_version` integer NOT NULL,
	`id` text NOT NULL,
	`logical_host_id` text NOT NULL,
	`store_id` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`aggregate_version` integer NOT NULL,
	`authority_version` integer NOT NULL,
	`effective_version` integer NOT NULL,
	`security_version` integer NOT NULL,
	`approval_id` text NOT NULL,
	`client_id` text,
	`verifier` blob NOT NULL,
	`purpose` text NOT NULL,
	`algorithm` text NOT NULL,
	`verifier_version` integer NOT NULL,
	`key_version` integer NOT NULL,
	`requested_role` text,
	`granted_role` text,
	`host_url` text,
	`client_label` text,
	`actor_id` text,
	`state` text NOT NULL,
	`expires_at` text NOT NULL,
	`consumed_at` text,
	PRIMARY KEY(`logical_host_id`, `id`),
	FOREIGN KEY (`logical_host_id`,`store_id`) REFERENCES `__caplets_storage_identity_v1`(`logical_host_id`,`store_id`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`logical_host_id`,`client_id`) REFERENCES `cp_client`(`logical_host_id`,`client_id`) ON UPDATE no action ON DELETE restrict,
	CONSTRAINT "cp_pending_approval_model_version_version_check" CHECK("__new_cp_pending_approval"."model_version" >= 0),
	CONSTRAINT "cp_pending_approval_id_nonempty_check" CHECK(length("__new_cp_pending_approval"."id") > 0),
	CONSTRAINT "cp_pending_approval_logical_host_id_nonempty_check" CHECK(length("__new_cp_pending_approval"."logical_host_id") > 0),
	CONSTRAINT "cp_pending_approval_store_id_nonempty_check" CHECK(length("__new_cp_pending_approval"."store_id") > 0),
	CONSTRAINT "cp_pending_approval_created_at_nonempty_check" CHECK(length("__new_cp_pending_approval"."created_at") > 0),
	CONSTRAINT "cp_pending_approval_updated_at_nonempty_check" CHECK(length("__new_cp_pending_approval"."updated_at") > 0),
	CONSTRAINT "cp_pending_approval_aggregate_version_version_check" CHECK("__new_cp_pending_approval"."aggregate_version" >= 0),
	CONSTRAINT "cp_pending_approval_authority_version_version_check" CHECK("__new_cp_pending_approval"."authority_version" >= 0),
	CONSTRAINT "cp_pending_approval_effective_version_version_check" CHECK("__new_cp_pending_approval"."effective_version" >= 0),
	CONSTRAINT "cp_pending_approval_security_version_version_check" CHECK("__new_cp_pending_approval"."security_version" >= 0),
	CONSTRAINT "cp_pending_approval_approval_id_nonempty_check" CHECK(length("__new_cp_pending_approval"."approval_id") > 0),
	CONSTRAINT "cp_pending_approval_client_id_nonempty_check" CHECK(length("__new_cp_pending_approval"."client_id") > 0),
	CONSTRAINT "cp_pending_approval_verifier_bytes_check" CHECK(length("__new_cp_pending_approval"."verifier") > 0),
	CONSTRAINT "cp_pending_approval_purpose_nonempty_check" CHECK(length("__new_cp_pending_approval"."purpose") > 0),
	CONSTRAINT "cp_pending_approval_algorithm_nonempty_check" CHECK(length("__new_cp_pending_approval"."algorithm") > 0),
	CONSTRAINT "cp_pending_approval_verifier_version_version_check" CHECK("__new_cp_pending_approval"."verifier_version" >= 0),
	CONSTRAINT "cp_pending_approval_key_version_version_check" CHECK("__new_cp_pending_approval"."key_version" >= 0),
	CONSTRAINT "cp_pending_approval_requested_role_nonempty_check" CHECK(length("__new_cp_pending_approval"."requested_role") > 0),
	CONSTRAINT "cp_pending_approval_granted_role_nonempty_check" CHECK(length("__new_cp_pending_approval"."granted_role") > 0),
	CONSTRAINT "cp_pending_approval_host_url_nonempty_check" CHECK(length("__new_cp_pending_approval"."host_url") > 0),
	CONSTRAINT "cp_pending_approval_client_label_nonempty_check" CHECK(length("__new_cp_pending_approval"."client_label") > 0),
	CONSTRAINT "cp_pending_approval_actor_id_nonempty_check" CHECK(length("__new_cp_pending_approval"."actor_id") > 0),
	CONSTRAINT "cp_pending_approval_state_nonempty_check" CHECK(length("__new_cp_pending_approval"."state") > 0),
	CONSTRAINT "cp_pending_approval_expires_at_nonempty_check" CHECK(length("__new_cp_pending_approval"."expires_at") > 0),
	CONSTRAINT "cp_pending_approval_consumed_at_nonempty_check" CHECK(length("__new_cp_pending_approval"."consumed_at") > 0),
	CONSTRAINT "cp_pending_approval_model_version_check" CHECK("__new_cp_pending_approval"."model_version" = 1)
);
--> statement-breakpoint
INSERT INTO `__new_cp_pending_approval`("model_version", "id", "logical_host_id", "store_id", "created_at", "updated_at", "aggregate_version", "authority_version", "effective_version", "security_version", "approval_id", "client_id", "verifier", "purpose", "algorithm", "verifier_version", "key_version", "requested_role", "granted_role", "host_url", "client_label", "actor_id", "state", "expires_at", "consumed_at") SELECT "model_version", "id", "logical_host_id", "store_id", "created_at", "updated_at", "aggregate_version", "authority_version", "effective_version", "security_version", "approval_id", "client_id", "verifier", 'pending-approval', 'legacy-invalidated', 0, 0, NULL, NULL, NULL, NULL, "actor_id", 'invalidated', "expires_at", COALESCE("consumed_at", "updated_at") FROM `cp_pending_approval`;--> statement-breakpoint
DROP TABLE `cp_pending_approval`;--> statement-breakpoint
ALTER TABLE `__new_cp_pending_approval` RENAME TO `cp_pending_approval`;--> statement-breakpoint
CREATE UNIQUE INDEX `cp_pending_approval_semantic_uq` ON `cp_pending_approval` (`logical_host_id`,`approval_id`);--> statement-breakpoint
CREATE INDEX `cp_pending_approval_query_1_idx` ON `cp_pending_approval` (`logical_host_id`,`state`,`expires_at`);