CREATE TABLE `cp_setup_approval` (
	`model_version` integer NOT NULL,
	`id` text NOT NULL,
	`logical_host_id` text NOT NULL,
	`store_id` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`aggregate_version` integer NOT NULL,
	`authority_version` integer NOT NULL,
	`effective_version` integer NOT NULL,
	`security_version` integer NOT NULL,
	`approval_id` text NOT NULL,
	`project_fingerprint` text NOT NULL,
	`caplet_id` text NOT NULL,
	`content_hash` text NOT NULL,
	`target_kind` text NOT NULL,
	`actor` text NOT NULL,
	`approved_at` text NOT NULL,
	PRIMARY KEY(`logical_host_id`, `id`),
	FOREIGN KEY (`logical_host_id`,`store_id`) REFERENCES `__caplets_storage_identity_v1`(`logical_host_id`,`store_id`) ON UPDATE no action ON DELETE restrict,
	CONSTRAINT "cp_setup_approval_model_version_version_check" CHECK("cp_setup_approval"."model_version" >= 0),
	CONSTRAINT "cp_setup_approval_id_nonempty_check" CHECK(length("cp_setup_approval"."id") > 0),
	CONSTRAINT "cp_setup_approval_logical_host_id_nonempty_check" CHECK(length("cp_setup_approval"."logical_host_id") > 0),
	CONSTRAINT "cp_setup_approval_store_id_nonempty_check" CHECK(length("cp_setup_approval"."store_id") > 0),
	CONSTRAINT "cp_setup_approval_created_at_nonempty_check" CHECK(length("cp_setup_approval"."created_at") > 0),
	CONSTRAINT "cp_setup_approval_updated_at_nonempty_check" CHECK(length("cp_setup_approval"."updated_at") > 0),
	CONSTRAINT "cp_setup_approval_aggregate_version_version_check" CHECK("cp_setup_approval"."aggregate_version" >= 0),
	CONSTRAINT "cp_setup_approval_authority_version_version_check" CHECK("cp_setup_approval"."authority_version" >= 0),
	CONSTRAINT "cp_setup_approval_effective_version_version_check" CHECK("cp_setup_approval"."effective_version" >= 0),
	CONSTRAINT "cp_setup_approval_security_version_version_check" CHECK("cp_setup_approval"."security_version" >= 0),
	CONSTRAINT "cp_setup_approval_approval_id_nonempty_check" CHECK(length("cp_setup_approval"."approval_id") > 0),
	CONSTRAINT "cp_setup_approval_project_fingerprint_nonempty_check" CHECK(length("cp_setup_approval"."project_fingerprint") > 0),
	CONSTRAINT "cp_setup_approval_caplet_id_nonempty_check" CHECK(length("cp_setup_approval"."caplet_id") > 0),
	CONSTRAINT "cp_setup_approval_content_hash_nonempty_check" CHECK(length("cp_setup_approval"."content_hash") > 0),
	CONSTRAINT "cp_setup_approval_target_kind_nonempty_check" CHECK(length("cp_setup_approval"."target_kind") > 0),
	CONSTRAINT "cp_setup_approval_actor_nonempty_check" CHECK(length("cp_setup_approval"."actor") > 0),
	CONSTRAINT "cp_setup_approval_approved_at_nonempty_check" CHECK(length("cp_setup_approval"."approved_at") > 0),
	CONSTRAINT "cp_setup_approval_model_version_check" CHECK("cp_setup_approval"."model_version" = 1)
);
--> statement-breakpoint
CREATE TABLE `cp_setup_attempt` (
	`model_version` integer NOT NULL,
	`id` text NOT NULL,
	`logical_host_id` text NOT NULL,
	`store_id` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`aggregate_version` integer NOT NULL,
	`authority_version` integer NOT NULL,
	`effective_version` integer NOT NULL,
	`security_version` integer NOT NULL,
	`attempt_id` text NOT NULL,
	`project_fingerprint` text NOT NULL,
	`caplet_id` text NOT NULL,
	`content_hash` text NOT NULL,
	`setup_hash` text,
	`target_kind` text NOT NULL,
	`status` text NOT NULL,
	`detail` text NOT NULL,
	`finished_at` text NOT NULL,
	PRIMARY KEY(`logical_host_id`, `id`),
	FOREIGN KEY (`logical_host_id`,`store_id`) REFERENCES `__caplets_storage_identity_v1`(`logical_host_id`,`store_id`) ON UPDATE no action ON DELETE restrict,
	CONSTRAINT "cp_setup_attempt_model_version_version_check" CHECK("cp_setup_attempt"."model_version" >= 0),
	CONSTRAINT "cp_setup_attempt_id_nonempty_check" CHECK(length("cp_setup_attempt"."id") > 0),
	CONSTRAINT "cp_setup_attempt_logical_host_id_nonempty_check" CHECK(length("cp_setup_attempt"."logical_host_id") > 0),
	CONSTRAINT "cp_setup_attempt_store_id_nonempty_check" CHECK(length("cp_setup_attempt"."store_id") > 0),
	CONSTRAINT "cp_setup_attempt_created_at_nonempty_check" CHECK(length("cp_setup_attempt"."created_at") > 0),
	CONSTRAINT "cp_setup_attempt_updated_at_nonempty_check" CHECK(length("cp_setup_attempt"."updated_at") > 0),
	CONSTRAINT "cp_setup_attempt_aggregate_version_version_check" CHECK("cp_setup_attempt"."aggregate_version" >= 0),
	CONSTRAINT "cp_setup_attempt_authority_version_version_check" CHECK("cp_setup_attempt"."authority_version" >= 0),
	CONSTRAINT "cp_setup_attempt_effective_version_version_check" CHECK("cp_setup_attempt"."effective_version" >= 0),
	CONSTRAINT "cp_setup_attempt_security_version_version_check" CHECK("cp_setup_attempt"."security_version" >= 0),
	CONSTRAINT "cp_setup_attempt_attempt_id_nonempty_check" CHECK(length("cp_setup_attempt"."attempt_id") > 0),
	CONSTRAINT "cp_setup_attempt_project_fingerprint_nonempty_check" CHECK(length("cp_setup_attempt"."project_fingerprint") > 0),
	CONSTRAINT "cp_setup_attempt_caplet_id_nonempty_check" CHECK(length("cp_setup_attempt"."caplet_id") > 0),
	CONSTRAINT "cp_setup_attempt_content_hash_nonempty_check" CHECK(length("cp_setup_attempt"."content_hash") > 0),
	CONSTRAINT "cp_setup_attempt_setup_hash_hash_check" CHECK(length("cp_setup_attempt"."setup_hash") = 64 AND NOT "cp_setup_attempt"."setup_hash" GLOB '*[^0-9a-f]*'),
	CONSTRAINT "cp_setup_attempt_target_kind_nonempty_check" CHECK(length("cp_setup_attempt"."target_kind") > 0),
	CONSTRAINT "cp_setup_attempt_status_nonempty_check" CHECK(length("cp_setup_attempt"."status") > 0),
	CONSTRAINT "cp_setup_attempt_detail_json_check" CHECK(json_valid("cp_setup_attempt"."detail")),
	CONSTRAINT "cp_setup_attempt_finished_at_nonempty_check" CHECK(length("cp_setup_attempt"."finished_at") > 0),
	CONSTRAINT "cp_setup_attempt_model_version_check" CHECK("cp_setup_attempt"."model_version" = 1)
);
